set(Plugin-Name "PET Dynamic DataFit Plugin")
set(Plugin-Version "1.0")
set(Plugin-Vendor "DKFZ, Software Development For Integrated Diagnostics and Therapy")
set(Plugin-ContactAddress "c.debus@dkfz.de")
set(Require-Plugin org.mitk.gui.qt.common)
