/*============================================================================

The Medical Imaging Interaction Toolkit (MITK)

Copyright (c) German Cancer Research Center (DKFZ)
All rights reserved.

Use of this source code is governed by a 3-clause BSD license that can be
found in the LICENSE file.

============================================================================*/

#ifndef mitknnInteractiveLassoInteractor_h
#define mitknnInteractiveLassoInteractor_h

#include <mitknnInteractiveInteractor.h>

namespace mitk
{
  class Image;
}

namespace mitk::nnInteractive
{
  /** \brief %nnInteractive interactor for drawing contours.
   *
   * Contours are managed as a list of ContourModel data nodes, organized
   * by PromptType. The most recently drawn contour is also available as a
   * binary image mask that serves as input for the nnInteractive model.
   *
   * Interaction is handled through an internal wrapper around the
   * AddContourTool. Unlike the other interactors, LassoInteractor does not
   * block left mouse button display interaction, as the underlying tool
   * uses its own state machine for mouse event handling.
   *
   * \sa Interactor, ContourModel, AddContourTool, nnInteractiveTool
   */
  class MITKPYTHONSEGMENTATION_EXPORT LassoInteractor : public Interactor
  {
  public:
    /** \brief Constructs a LassoInteractor with InteractionType::Lasso.
     */
    LassoInteractor();

    /** \brief Destructor. Calls OnReset() to clean up data nodes.
     */
    ~LassoInteractor() override;

    /** \brief Checks whether any contours have been drawn.
     *
     * \return \c true if at least one completed contour exists for any prompt
     *         type, \c false otherwise.
     */
    bool HasInteractions() const override;

    /** \brief Returns the binary mask of the most recently drawn contour.
     *
     * The mask is a MultiLabelSegmentation group image generated by the
     * internal lasso tool from the last completed contour.
     *
     * \return Pointer to the mask Image, or \c nullptr if no mask node exists.
     *
     * \pre At least one contour must have been drawn.
     */
    const Image* GetLastLassoMask() const;

  private:
    void OnSetToolManager() override;
    void OnHandleEvent(InteractionEvent* event) override;
    void OnEnable() override;
    void OnDisable() override;
    void OnReset() override;

    class Impl;
    std::unique_ptr<Impl> m_Impl;
  };
}

#endif
