set(H_FILES
  include/mitkIRestServerService.h
  include/mitkRestServerConfig.h
  include/mitkRestServer.h
  include/mitkDataStorageBridge.h
  include/mitkNodeUidMapper.h
  include/mitkNodeQueryParams.h
  include/mitkErrorResponse.h
)

set(CPP_FILES
  mitkIRestServerService.cpp
  mitkRestServer.cpp
  mitkDataStorageBridge.cpp
  mitkNodeUidMapper.cpp
  mitkErrorResponse.cpp
  mitkHealthController.cpp
  mitkDataStorageController.cpp
  mitkSwaggerController.cpp
  mitkRenderingController.cpp
)

set(RESOURCE_FILES
  openapi.json
  swagger/index.html
  swagger/swagger-ui-bundle.js
  swagger/swagger-ui.css
  swagger/LICENSE
)
