/*===================================================================

BlueBerry Platform

Copyright (c) German Cancer Research Center,
Division of Medical and Biological Informatics.
All rights reserved.

This software is distributed WITHOUT ANY WARRANTY; without
even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.

See LICENSE.txt or http://www.mitk.org for details.

===================================================================*/

#include "berryICommandService.h"

#include "berryCommandManager.h"

namespace berry {

const QString ICommandService::AUTOGENERATED_CATEGORY_ID()
{
  static QString str(CommandManager::AUTOGENERATED_CATEGORY_ID);
  return str;
}

}
