set(Plugin-Name "MITK PlanarFigure")
set(Plugin-Version "0.1")
set(Plugin-Vendor "DKFZ, Medical and Biological Informatics")
set(Plugin-ContactAddress "http://www.mitk.org")
set(Require-Plugin org.mitk.gui.common)
set(Plugin-ActivationPolicy eager)
