set(CPP_FILES
  mitkLegacyLabelSetImageIO.cpp
  mitkMultilabelActivator.cpp
  mitkMultilabelIOMimeTypes.cpp
  mitkMultiLabelSegmentationIO.cpp
  mitkMultiLabelSegmentationSerializer.cpp
  mitkMultiLabelSegmentationStackWriterBase.cpp
  mitkMultiLabelSegmentationStackNiftiWriter.cpp
  mitkMultiLabelSegmentationStackReader.cpp
)
