set(CPP_FILES
  mitkLegacyLabelSetImageIO.cpp
  mitkLegacyLabelSetImageIO.h
  mitkMultiLabelSegmentationIO.cpp
  mitkMultiLabelSegmentationIO.h
  mitkMultiLabelSegmentationSerializer.cpp
  mitkMultiLabelSegmentationSerializer.h
  mitkMultilabelActivator.cpp
  mitkMultilabelIOMimeTypes.cpp
  mitkMultilabelIOMimeTypes.h
  mitkSegmentationTaskListIO.cpp
  mitkSegmentationTaskListIO.h
  mitkSegmentationTaskListSerializer.cpp
  mitkSegmentationTaskListSerializer.h
)
