set(CPP_FILES
  mitkLabelSetImageIO.cpp
  mitkLabelSetImageIO.h
  mitkLabelSetImageSerializer.cpp
  mitkLabelSetImageSerializer.h
  mitkMultilabelActivator.cpp
  mitkMultilabelIOMimeTypes.cpp
  mitkMultilabelIOMimeTypes.h
  mitkSegmentationTaskIO.cpp
  mitkSegmentationTaskIO.h
  mitkSegmentationTaskSerializer.cpp
  mitkSegmentationTaskSerializer.h
)
