MACRO(FIND_POCO)

FIND_PATH(POCO_PATH poco DOC "Base directory of the POCO library")
FIND_PATH(POCO_INCLUDE_DIR Poco DOC "Base include directory of the POCO library.")

IF(POCO_INCLUDE_DIR)
  SET(POCO_INCLUDE_DIRS
   ${POCO_INCLUDE_DIR}
  )
ENDIF(POCO_INCLUDE_DIR)

IF(POCO_PATH)
  LINK_DIRECTORIES(${POCO_PATH}/lib)
ENDIF(POCO_PATH)

ENDMACRO(FIND_POCO)
