set(Plugin-Name "MITK Deformable Registration")
set(Plugin-Version "1.0")
set(Plugin-Vendor "DKFZ, Medical and Biological Informatics")
set(Plugin-ContactAddress "www.mitk.org")
set(Require-Plugin org.mitk.gui.qt.common)
