# The entries in the mitk_modules list must be
# ordered according to their dependencies.

set(mitk_modules
  Core
  CommandLine
  AppUtil
  DCMTesting
  RDF
  LegacyIO
  DataTypesExt
  Annotation
  LegacyGL
  AlgorithmsExt
  MapperExt
  DICOMReader
  DICOMReaderServices
  DICOMTesting
  SceneSerializationBase
  PlanarFigure
  ImageDenoising
  ImageExtraction
  SceneSerialization
  Gizmo
  GraphAlgorithms
  Multilabel
  ImageStatistics
  ContourModel
  SurfaceInterpolation
  Segmentation
  PlanarFigureSegmentation
  QtWidgets
  QtWidgetsExt
  Chart
  SegmentationUI
  Classification
  GPGPU
  OpenIGTLink
  IGTBase
  IGT
  CameraCalibration
  OpenCL
  OpenCVVideoSupport
  QtOverlays
  ToFHardware
  ToFProcessing
  ToFUI
  PhotoacousticsHardware
  PhotoacousticsAlgorithms
  PhotoacousticsLib
  US
  USUI
  DicomUI
  Remeshing
  Python
  QtPython
  Persistence
  OpenIGTLinkUI
  IGTUI
  DicomRT
  RTUI
  IOExt
  XNAT
  TubeGraph
  BiophotonicsHardware
  MatchPointRegistration
  MatchPointRegistrationUI
  DiffusionImaging
  TumorInvasionAnalysis
  BoundingShape
  RenderWindowManager
  RenderWindowManagerUI
  CEST
  DICOMQI
)

if(MITK_ENABLE_PIC_READER)
  list(APPEND mitk_modules IpPicSupportIO)
endif()
