set(MOC_H_FILES
  src/internal/berryPluginActivator.h
)

set(CPP_FILES
  src/berryIJobChangeListener.cpp
  src/berryIJobManager.cpp
  src/berryJob.cpp
  src/berryJobExceptions.cpp
  src/berryJobStatus.cpp
  src/berryMultiRule.cpp
  src/berryNullProgressMonitor.cpp
  src/berryProgressProvider.cpp
  src/berryQualifiedName.cpp
  src/internal/berryInternalJob.cpp
  src/internal/berryJobChangeEvent.cpp
  src/internal/berryJobListeners.cpp
  src/internal/berryJobManager.cpp
  src/internal/berryJobQueue.cpp
  src/internal/berryPluginActivator.cpp
  src/internal/berryWorker.cpp
  src/internal/berryWorkerPool.cpp
)

set(H_FILES
  src/berryILock.h
  src/berryIProgressMonitor.h
  src/berryISchedulingRule.h
  src/berryLockListener.h
)
