set(CTEST_PROJECT_NAME_SUPERBUILD "MITK-superbuild")
set(CTEST_PROJECT_NAME "MITK")
set(CTEST_NIGHTLY_START_TIME "23:00:00 EDT")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "cdash.mitk.org")
set(CTEST_DROP_LOCATION "/submit.php?project=MITK")
set(CTEST_DROP_SITE_CDASH TRUE)

