SET(QMITK_CPP
    # main.cpp
  # mitkNavigator.cpp
  # mitkSliderNavigator.cpp
  popupactionhistory.cpp
  popupundoredo.cpp
  QmitkAlgorithmFunctionalityComponent.cpp
  QmitkBaseAlgorithmComponent.cpp
  QmitkBaseFunctionalityComponent.cpp
  QmitkCallbackFromGUIThread.cpp
  QmitkColorTransferFunctionCanvas.cpp
  QmitkFctCompMediator.cpp
  QmitkFunctionalityComponentContainer.cpp
  QmitkHelpBrowser.cpp
  QmitkInteractionFunctionalityComponent.cpp
  QmitkLevelWindowWidgetContextMenu.cpp
  QmitkLineEditLevelWindowWidget.cpp
  QmitkPiecewiseFunctionCanvas.cpp
  QmitkPropertyListViewItem.cpp
  QmitkRenderingManager.cpp
  QmitkRenderingManagerFactory.cpp
  QmitkRenderWindow.cpp
  QmitkSliderLevelWindowWidget.cpp
  QmitkStatusBar.cpp
  QmitkStepperAdapter.cpp
  QmitkTransferFunctionCanvas.cpp
  QmitkUndoRedoButton.cpp
  qundoredobutton.cpp
  VtkQRenderWindowInteractor.cpp
)
SET(QMITK_UI
  QmitkFunctionalityComponentContainerGUI.ui
  QmitkLevelWindowPresetDefinition.ui
  QmitkLevelWindowRangeChange.ui
  QmitkLevelWindowWidget.ui
  QmitkMaterialEditor.ui
  QmitkMaterialShowcase.ui
  QmitkPointListWidget.ui
  QmitkPrimitiveMovieNavigator.ui
  QmitkPropertyListView.ui
  QmitkSelectableGLWidget.ui
  QmitkSliceWidget.ui
  QmitkSliderNavigator.ui
  QmitkStdMultiWidget.ui
  QmitkTransferFunctionWidget.ui
  QmitkTwoButtonNavigator.ui
  QmitkVolumetryWidget.ui
)
SET(QMITK_MOC_H
  popupactionhistory.h
  popupundoredo.h
  QmitkAlgorithmFunctionalityComponent.h
  QmitkBaseFunctionalityComponent.h
  QmitkCallbackFromGUIThread.h
  QmitkColorTransferFunctionCanvas.h
  QmitkFctCompMediator.h
  QmitkFunctionalityComponentContainer.h
  QmitkHelpBrowser.h
  QmitkInteractionFunctionalityComponent.h
  QmitkLevelWindowWidgetContextMenu.h
  QmitkLineEditLevelWindowWidget.h
  QmitkPiecewiseFunctionCanvas.h
  QmitkPropertyListViewItem.h
  QmitkRenderingManager.h
  QmitkSliderLevelWindowWidget.h
  QmitkStepperAdapter.h
  QmitkTransferFunctionCanvas.h
  QmitkUndoRedoButton.h
  qundoredobutton.h
)
