SET(MITK_EXT_PLUGINS
  org.mitk.core.ext:OFF
  org.mitk.core.jobs:OFF
  org.mitk.planarfigure:ON
  org.mitk.diffusionimaging:OFF
  org.mitk.gui.qt.examples:OFF
  org.mitk.gui.qt.ext:OFF
  org.mitk.gui.qt.extapplication:OFF
  org.mitk.gui.qt.datamanager:ON
  org.mitk.gui.qt.segmentation:OFF
  org.mitk.gui.qt.diffusionimaging:OFF
  org.mitk.gui.qt.dtiatlasapp:OFF
  org.mitk.gui.qt.diffusionimagingapp:OFF
  org.mitk.gui.qt.igttoolpairnavigation:OFF
  org.mitk.gui.qt.igttrackinglab:OFF
  org.mitk.gui.qt.igttracking:OFF
  org.mitk.gui.qt.basicimageprocessing:OFF
  org.mitk.gui.qt.igttutorial:OFF
  org.mitk.gui.qt.tofutil:OFF
  org.mitk.gui.qt.toftutorial:OFF
  org.mitk.gui.qt.imagenavigator:ON
  org.mitk.gui.qt.moviemaker:OFF
  org.mitk.gui.qt.imagestatistics:OFF
  org.mitk.gui.qt.materialeditor:OFF
  org.mitk.gui.qt.ugvisualization:OFF
  org.mitk.gui.qt.measurement:OFF
  org.mitk.gui.qt.imagecropper:OFF
  org.mitk.gui.qt.volumevisualization:OFF
  org.mitk.gui.qt.pointsetinteraction:OFF
  org.mitk.gui.qt.videoplayer:OFF
  org.mitk.gui.qt.python.console:OFF
  org.mitk.gui.qt.registration:OFF
  )
