SET(MITK_EXT_PLUGINS
  org.mitk.core.ext:ON
  org.mitk.core.jobs:OFF
  org.mitk.diffusionimaging:OFF
  org.mitk.gui.qt.diffusionimaging:OFF
  org.mitk.gui.qt.ext:ON
  org.mitk.gui.qt.extapplication:ON
  org.mitk.planarfigure:ON
  org.mitk.gui.qt.datamanager:ON
  org.mitk.gui.qt.simpleexample:OFF
  )
