SET(MITK_EXT_PLUGINS
  org.mitk.core.ext:ON
  org.mitk.core.jobs:OFF
  org.mitk.diffusionimaging:OFF
  org.mitk.gui.qt.diffusionimaging:OFF
  org.mitk.gui.qt.ext:ON
  org.mitk.gui.qt.extapplication:ON
  org.mitk.gui.qt.segmentation:OFF
  org.mitk.planarfigure:ON
  org.mitk.gui.qt.datamanager:ON
  org.mitk.gui.qt.igtnavigationtoolmanager:OFF
  org.mitk.gui.qt.igttoolpairnavigation:ON
  org.mitk.gui.qt.igttrackingtoolbox:OFF
  org.mitk.gui.qt.regiongrowing:OFF
  org.mitk.gui.qt.navigationdataplayer:ON
  org.mitk.gui.qt.basicimageprocessing:OFF
  org.mitk.gui.qt.colourimageprocessing:OFF
  org.mitk.gui.qt.tofutil:OFF
  org.mitk.gui.qt.imagenavigator:ON
  org.mitk.gui.qt.moviemaker:ON
  org.mitk.gui.qt.deformableregistration:ON
  org.mitk.gui.qt.rigidregistration:ON
  org.mitk.gui.qt.pointbasedregistration:ON
  )
