set(Plugin-Name "MITK Semantic relations")
set(Plugin-Version "0.1")
set(Plugin-Vendor "DKFZ")
set(Plugin-ContactAddress "http://www.mitk.org")
set(Require-Plugin org.mitk.gui.qt.common org.mitk.gui.qt.application)
