/*============================================================================

The Medical Imaging Interaction Toolkit (MITK)

Copyright (c) German Cancer Research Center (DKFZ)
All rights reserved.

Use of this source code is governed by a 3-clause BSD license that can be
found in the LICENSE file.

============================================================================*/

#ifndef mitkCone_h
#define mitkCone_h

#include <MitkDataTypesExtExports.h>
#include <mitkBoundingObject.h>

namespace mitk
{
  /**
   * \brief Bounding object shaped as a cone.
   *
   * The cone has radius 1, height 2, is centered at the origin, and points
   * along the negative Y-axis. The surface is generated by vtkConeSource.
   * Volume is calculated as pi/3 * rx * rz * h using the geometry extents.
   *
   * \sa BoundingObject, Cuboid, Cylinder, Ellipsoid
   * \ingroup Data
   */
  class MITKDATATYPESEXT_EXPORT Cone : public BoundingObject
  {
  public:
    mitkClassMacro(Cone, BoundingObject);
    itkFactorylessNewMacro(Self);
    itkCloneMacro(Self);

    /**
     * \brief Calculate the cone volume from the geometry extents.
     * \return The volume in world-coordinate units cubed.
     */
    mitk::ScalarType GetVolume() override;

    /**
     * \brief Test whether a world-coordinate point lies inside the cone.
     *
     * The point is transformed to object coordinates before evaluation.
     *
     * \param[in] p The point in world coordinates.
     * \return true if the point is inside.
     */
    bool IsInside(const Point3D &p) const override;
  protected:
    Cone();
    ~Cone() override;
  };
}
#endif
