/*============================================================================

The Medical Imaging Interaction Toolkit (MITK)

Copyright (c) German Cancer Research Center (DKFZ)
All rights reserved.

Use of this source code is governed by a 3-clause BSD license that can be
found in the LICENSE file.

============================================================================*/

#ifndef mitkLabeledImageLookupTable_h
#define mitkLabeledImageLookupTable_h

#include <MitkDataTypesExtExports.h>
#include <mitkLevelWindow.h>
#include <mitkLookupTable.h>
#include <iostream>
#include <string>

namespace mitk
{
  /**
   * \brief Lookup table for 2D rendering of labeled (segmented) images.
   *
   * Supports images with up to 256 unsigned labels (0--255). Label 0 is
   * treated as background and is fully transparent by default. All other
   * labels are initialized with random colors.
   *
   * For correct color mapping in 2D renderers, use the level/window settings
   * returned by GetLevelWindow().
   *
   * \sa LookupTable
   * \ingroup Data
   */
  class MITKDATATYPESEXT_EXPORT LabeledImageLookupTable : public LookupTable
  {
  public:
    /**
     * Standard mitk typedefs are generated by the mitkClassMacro
     */
    mitkClassMacro(LabeledImageLookupTable, LookupTable);

    /**
     * Make this object constructable by the ::%New() Method.
     */
    itkFactorylessNewMacro(Self);
    itkCloneMacro(Self);

      /**
       * The data type for a label. Currently only images with labels
       * in the range [0,255] are supported.
       */
      typedef unsigned char LabelType;

    /**
     * \brief Assignment from a generic LookupTable.
     * \param[in] other The lookup table to copy from.
     * \return Reference to this object.
     */
    LabeledImageLookupTable &operator=(const LookupTable &other) override;

    /**
     * \brief Set the RGBA color for a given label.
     *
     * \param[in] label The pixel value used as a label in the image.
     * \param[in] r Red component in [0, 1].
     * \param[in] g Green component in [0, 1].
     * \param[in] b Blue component in [0, 1].
     * \param[in] a Alpha component in [0, 1]. Default is 1.0 (fully opaque).
     */
    virtual void SetColorForLabel(
      const LabelType &label, const double &r, const double &g, const double &b, const double a = 1.0);

    /**
     * \brief Get the RGBA color assigned to a given label.
     *
     * \param[in] label The label value.
     * \return Pointer to a four-element RGBA array with components in [0, 1].
     */
    virtual double *GetColorForLabel(const LabelType &label);

    /**
     * \brief Get the LevelWindow settings required for correct 2D color mapping.
     *
     * When visualizing labeled images in 2D, use these level/window settings
     * to ensure that scalar values are mapped to the correct colors.
     *
     * \return The configured LevelWindow.
     */
    mitk::LevelWindow GetLevelWindow() { return m_LevelWindow; }
  protected:
    /**
     * Default constructor. Protected to prevent "normal" creation
     */
    LabeledImageLookupTable();

    LabeledImageLookupTable(const LabeledImageLookupTable &other);

    /**
     * Virtual destructor
     */
    ~LabeledImageLookupTable() override;

    /**
     * Generates a random rgb color value. Values for rgb are in the range
     * [0,1]
     */
    virtual void GenerateRandomColor(double &r, double &g, double &b);
    /**
     * Generates a radnom number drawn from a uniform
     * distribution in the range [0,1].
     */
    virtual double GenerateRandomNumber();

    mitkCloneMacro(LabeledImageLookupTable);

    mitk::LevelWindow m_LevelWindow;
  };
}

#endif
