/*============================================================================

The Medical Imaging Interaction Toolkit (MITK)

Copyright (c) German Cancer Research Center (DKFZ)
All rights reserved.

Use of this source code is governed by a 3-clause BSD license that can be
found in the LICENSE file.

============================================================================*/

#ifndef mitkCylinder_h
#define mitkCylinder_h

#include <MitkDataTypesExtExports.h>
#include <mitkBoundingObject.h>

namespace mitk
{
  /**
   * \brief Bounding object shaped as a cylinder.
   *
   * The cylinder has radius 1, height 2, is centered at the origin, and
   * aligned along the Y-axis. The surface is generated by vtkCylinderSource.
   * Volume is calculated as pi * rx * rz * h using the geometry extents.
   *
   * \sa BoundingObject, Cone, Cuboid, Ellipsoid
   * \ingroup Data
   */
  class MITKDATATYPESEXT_EXPORT Cylinder : public BoundingObject
  {
  public:
    mitkClassMacro(Cylinder, BoundingObject);
    itkFactorylessNewMacro(Self);
    itkCloneMacro(Self);

    /**
     * \brief Calculate the cylinder volume from the geometry extents.
     * \return The volume in world-coordinate units cubed.
     */
    mitk::ScalarType GetVolume() override;

    /**
     * \brief Test whether a world-coordinate point lies inside the cylinder.
     *
     * The point is transformed to object coordinates before evaluation.
     *
     * \param[in] p The point in world coordinates.
     * \return true if the point is inside.
     */
    bool IsInside(const Point3D &p) const override;

  protected:
    Cylinder();
    ~Cylinder() override;
  };
}
#endif
