set(BUILD_TESTING OFF CACHE BOOL "" FORCE)

set(MITK_USE_BLUEBERRY OFF CACHE BOOL "" FORCE)
set(MITK_USE_CTK OFF CACHE BOOL "" FORCE)
set(MITK_USE_Qt5 OFF CACHE BOOL "" FORCE)
set(MITK_USE_Qwt OFF CACHE BOOL "" FORCE)
