/*============================================================================

The Medical Imaging Interaction Toolkit (MITK)

Copyright (c) German Cancer Research Center (DKFZ)
All rights reserved.

Use of this source code is governed by a 3-clause BSD license that can be
found in the LICENSE file.

============================================================================*/

#ifndef mitkLabel_h
#define mitkLabel_h

#include "MitkMultilabelExports.h"
#include <mitkColorProperty.h>
#include <mitkPropertyList.h>
#include <mitkPoint.h>
#include <mitkVector.h>

namespace mitk
{
  //##
  //##Documentation
  //## @brief A data structure describing a label.
  //## @ingroup Data
  //##
  class MITKMULTILABEL_EXPORT Label : public PropertyList
  {
  public:
    mitkClassMacro(Label, mitk::PropertyList);

    typedef unsigned short PixelType;

    itkNewMacro(Self);
    mitkNewMacro2Param(Self, PixelType, const std::string&);

    /// The maximum value a label can get: Since the value is of type unsigned short MAX_LABEL_VALUE = 65535
    static const PixelType MAX_LABEL_VALUE;

    //** Value indicating pixels that are not labeled at all.*/
    static constexpr PixelType UNLABELED_VALUE = 0;

    void SetLocked(bool locked);
    bool GetLocked() const;

    void SetVisible(bool visible);
    bool GetVisible() const;

    void SetOpacity(float opacity);
    float GetOpacity() const;

    void SetName(const std::string &name);
    std::string GetName() const;

    void SetTrackingID(const std::string& trackingID);
    std::string GetTrackingID() const;

    void SetTrackingUID(const std::string& trackingUID);
    std::string GetTrackingUID() const;

    void SetDescription(const std::string& description);
    std::string GetDescription() const;

    void SetCenterOfMassIndex(const mitk::Point3D &center);
    mitk::Point3D GetCenterOfMassIndex() const;

    void SetCenterOfMassCoordinates(const mitk::Point3D &center);
    mitk::Point3D GetCenterOfMassCoordinates() const;

    void SetColor(const mitk::Color &);
    const mitk::Color &GetColor() const;

    void SetValue(PixelType pixelValue);
    PixelType GetValue() const;

    enum class AlgorithmType
    {
      /// undefined type
      Undefined = 0,
      /// user generated labels with simple tooling (e.g. Add tool)
      MANUAL,
      /// calculated label by user with algorithmic assistance (e.g. nnInteractive)
      SEMIAUTOMATIC,
      /// fully automatically generated by an algorithm (e.g. nnUnet)
      AUTOMATIC
    };

    void SetAlgorithmType(AlgorithmType algoType);
    AlgorithmType GetAlgorithmType() const;
    std::string GetAlgorithmTypeStr() const;
    void SetAlgorithmName(const std::string& algoName);
    std::string GetAlgorithmName() const;

    /** @brief Helper function to add the usage of multiple tools correctly to the label.
     Mixture of types always lead to semiautomatic. If the algorithm name is empty, the name
     will directly set. If it is not empty and algoName is not already a sub string of the
     current algorithm name, the new algoName will be appended (separated by "|").
     */
    void AddToolUse(AlgorithmType algoType, const std::string& algoName);

    void SetProperty(const std::string &propertyKey, BaseProperty *property, const std::string &contextName = "", bool fallBackOnDefaultContext = false) override;
    BaseProperty::ConstPointer GetConstProperty(const std::string& propertyKey, const std::string& contextName = "", bool fallBackOnDefaultContext = true) const override;
    BaseProperty* GetNonConstProperty(const std::string& propertyKey, const std::string& contextName = "", bool fallBackOnDefaultContext = true) override;

    using itk::Object::Modified;
    void Modified() { Superclass::Modified(); }

    /** @brief Function updates the property values of a label provided as templates.
    If a property exists in the destination label only the value will be updated (therefor observers and pointers
    stay valid). If the property does not exist, it will be cloned and added. No properties will be removed.
    @param templateLabel Label instance that provides the new values for properties
    @param updateLabelValue Indicate if also the label value should be updated.
    */
    void Update(const Label* templateLabel, bool updateLabelValue = false);

    Label();
    Label(PixelType value, const std::string& name);
    ~Label() override;

  protected:
    void PrintSelf(std::ostream &os, itk::Indent indent) const override;
    using PropertyList::GetProperty;

    Label(const Label &other);

  private:
    PixelType m_Value;
    itk::LightObject::Pointer InternalClone() const override;
  };

  using LabelVector = std::vector<Label::Pointer>;
  using ConstLabelVector = std::vector<Label::ConstPointer>;

  /**
  * @brief Equal A function comparing two labels for being equal in data
  *
  * @ingroup MITKTestingAPI
  *
  * Following aspects are tested for equality:
  *  - Lebel equality via Equal-PropetyList
  *
  * @param rightHandSide An image to be compared
  * @param leftHandSide An image to be compared
  * @param eps Tolarence for comparison. You can use mitk::eps in most cases.
  * @param verbose Flag indicating if the user wants detailed console output or not.
  * @return true, if all subsequent comparisons are true, false otherwise
  */
  MITKMULTILABEL_EXPORT bool Equal(const mitk::Label &leftHandSide,
                                   const mitk::Label &rightHandSide,
                                   ScalarType eps,
                                   bool verbose);

} // namespace mitk

#endif
