set(CPP_FILES
  Algorithms/mitkCalculateSegmentationVolume.cpp
  Algorithms/mitkContourModelSetToImageFilter.cpp
  Algorithms/mitkContourSetToPointSetFilter.cpp
  Algorithms/mitkContourUtils.cpp
  Algorithms/mitkCorrectorAlgorithm.cpp
  Algorithms/mitkDiffImageApplier.cpp
  Algorithms/mitkDiffSliceOperation.cpp
  Algorithms/mitkDiffSliceOperationApplier.cpp
  Algorithms/mitkFeatureBasedEdgeDetectionFilter.cpp
  Algorithms/mitkGrowCutSegmentationFilter.cpp
  Algorithms/mitkImageLiveWireContourModelFilter.cpp
  Algorithms/mitkImageToContourFilter.cpp
  #Algorithms/mitkImageToContourModelFilter.cpp
  Algorithms/mitkImageToLiveWireContourFilter.cpp
  Algorithms/mitkManualSegmentationToSurfaceFilter.cpp
  Algorithms/mitkOtsuSegmentationFilter.cpp
  Algorithms/mitkSegmentationHelper.cpp
  Algorithms/mitkSegmentationObjectFactory.cpp
  Algorithms/mitkShapeBasedInterpolationAlgorithm.cpp
  Algorithms/mitkShowSegmentationAsSmoothedSurface.cpp
  Algorithms/mitkShowSegmentationAsSurface.cpp
  Algorithms/mitkVtkImageOverwrite.cpp
  Controllers/mitkSegmentationInterpolationController.cpp
  Controllers/mitkToolManager.cpp
  Controllers/mitkSegmentationModuleActivator.cpp
  Controllers/mitkToolManagerProvider.cpp
  DataManagement/mitkContour.cpp
  DataManagement/mitkContourSet.cpp
  DataManagement/mitkExtrudedContour.cpp
  Interactions/mitkAddContourTool.cpp
  Interactions/mitkAutoCropTool.cpp
  Interactions/mitkSegWithPreviewTool.cpp
  Interactions/mitkBinaryThresholdBaseTool.cpp
  Interactions/mitkBinaryThresholdTool.cpp
  Interactions/mitkBinaryThresholdULTool.cpp
  Interactions/mitkCloseRegionTool.cpp
  Interactions/mitkContourModelInteractor.cpp
  Interactions/mitkContourModelLiveWireInteractor.cpp
  Interactions/mitkEditableContourTool.cpp
  Interactions/mitkLiveWireTool2D.cpp
  Interactions/mitkLassoTool.cpp
  Interactions/mitkContourTool.cpp
  Interactions/mitkDrawPaintbrushTool.cpp
  Interactions/mitkErasePaintbrushTool.cpp
  Interactions/mitkEraseRegionTool.cpp
  Interactions/mitkFeedbackContourTool.cpp
  Interactions/mitkFillRegionBaseTool.cpp
  Interactions/mitkFillRegionTool.cpp
  Interactions/mitkGrowCutTool.cpp
  Interactions/mitkOtsuTool3D.cpp
  Interactions/mitkPaintbrushTool.cpp
  Interactions/mitkRegionGrowingTool.cpp
  Interactions/mitkSegmentationsProcessingTool.cpp
  Interactions/mitkSegTool2D.cpp
  Interactions/mitkSubtractContourTool.cpp
  Interactions/mitkTool.cpp
  Interactions/mitkToolCommand.cpp
  Interactions/mitkPickingTool.cpp
  Interactions/mitknnUnetTool.cpp
  Interactions/mitkProcessExecutor.cpp
  Interactions/mitkTotalSegmentatorTool.cpp
  Rendering/mitkContourMapper2D.cpp
  Rendering/mitkContourSetMapper2D.cpp
  Rendering/mitkContourSetVtkMapper3D.cpp
  Rendering/mitkContourVtkMapper3D.cpp
  SegmentationUtilities/BooleanOperations/mitkBooleanOperation.cpp
  SegmentationUtilities/MorphologicalOperations/mitkMorphologicalOperations.cpp
#Added from ML
  Controllers/mitkSliceBasedInterpolationController.cpp
  Algorithms/mitkSurfaceStampImageFilter.cpp
)

set(RESOURCE_FILES
  Add.svg
  Add_Cursor.svg
  AI.svg
  AI_Cursor.svg
  Close.svg
  Close_Cursor.svg
  Erase.svg
  Erase_Cursor.svg
  Fill.svg
  Fill_Cursor.svg
  LiveWire.svg
  LiveWire_Cursor.svg
  Lasso.svg
  GrowCut.svg
  Lasso_Cursor.svg
  Otsu.svg
  Paint.svg
  Paint_Cursor.svg
  Picking.svg
  RegionGrowing.svg
  RegionGrowing_Cursor.svg
  Subtract.svg
  Subtract_Cursor.svg
  Threshold.svg
  ULThreshold.svg
  Wipe.svg
  Wipe_Cursor.svg

  Interactions/dummy.xml
  Interactions/EditableContourTool.xml
  Interactions/PickingTool.xml
  Interactions/MouseReleaseOnly.xml
  Interactions/PressMoveRelease.xml
  Interactions/PressMoveReleaseAndPointSetting.xml
  Interactions/PressMoveReleaseWithCTRLInversion.xml
  Interactions/PressMoveReleaseWithCTRLInversionAllMouseMoves.xml
  Interactions/SegmentationConfig.xml
  Interactions/SegmentationInteraction.xml
  Interactions/SegmentationToolsConfig.xml

  Interactions/ContourModelModificationConfig.xml
  Interactions/ContourModelModificationInteractor.xml
)
