function(FunctionInstallThirdPartyCTKPlugins)

  macro_parse_arguments(_INSTALL "EXCLUDE" "" ${ARGN})

  set(install_directories "")
  if(NOT MACOSX_BUNDLE_NAMES)
    set(install_directories bin/plugins)
  else()
    foreach(bundle_name ${MACOSX_BUNDLE_NAMES})
      list(APPEND install_directories ${bundle_name}.app/Contents/MacOS/plugins)
    endforeach(bundle_name)
  endif(NOT MACOSX_BUNDLE_NAMES)

  if(_INSTALL_DEFAULT_ARGS)
    set(_ctk_plugins )
    foreach(_ctk_plugin ${_INSTALL_DEFAULT_ARGS})
      string(REPLACE "." "_" _plugin_target ${_ctk_plugin})
      list(APPEND _ctk_plugins ${_ctk_plugin})
    endforeach()
  else()
    ctkFunctionGetAllPluginTargets(_ctk_plugins)
  endif()

  if(_INSTALL_EXCLUDE)
    set(_exclude_list )
    foreach(_exclude ${_INSTALL_EXCLUDE})
      string(REPLACE "." "_" _exclude_target ${_exclude})
      list(APPEND _exclude_list ${_exclude_target})
    endforeach()
    list(REMOVE_ITEM _ctk_plugins ${_INSTALL_EXCLUDE})
  endif()

  ctkMacroGetAllNonProjectTargetLibraries("${_ctk_plugins}" _third_party_ctk_plugins)
  if(_third_party_ctk_plugins)
    foreach(install_subdir ${install_directories})
      MACRO_INSTALL_CTK_PLUGIN(TARGETS ${_third_party_ctk_plugins}
                               DESTINATION "${install_subdir}")
    endforeach()
  endif()
  
endfunction()
