set(CPP_FILES
  mitkDICOMSegmentationConstants.cpp
  mitkDICOMSegmentationPropertyHelper.cpp
  mitkLabel.cpp
  mitkLabelHighlightGuard.cpp
  mitkLabelSetImage.cpp
  mitkLabelSetImageConverter.cpp
  mitkLabelSetImageHelper.cpp
  mitkLabelSetImageSource.cpp
  mitkLabelSetImageSurfaceStampFilter.cpp
  mitkLabelSetImageToSurfaceFilter.cpp
  mitkLabelSetImageToSurfaceThreadedFilter.cpp
  mitkLabelSetImageVtkMapper2D.cpp
  mitkMultiLabelEvents.cpp
  mitkMultiLabelIOHelper.cpp
  mitkMultilabelObjectFactory.cpp
  mitkMultiLabelPredicateHelper.cpp
  mitkMultiLabelSegmentationVtkMapper3D.cpp
)
