set(CPP_FILES
  mitkClusteredPlaneSuggestionFilter.cpp
  mitkComputeContourSetNormalsFilter.cpp
  mitkCreateDistanceImageFromSurfaceFilter.cpp
  mitkPointCloudScoringFilter.cpp
  mitkImageToPointCloudFilter.cpp
  mitkReduceContourSetFilter.cpp
  mitkSurfaceInterpolationController.cpp
)
