set(CPP_FILES
  mitkComputeContourSetNormalsFilter.cpp
  mitkCreateDistanceImageFromSurfaceFilter.cpp
  mitkImageToPointCloudFilter.cpp
  mitkPlaneProposer.cpp
  mitkPointCloudScoringFilter.cpp
  mitkReduceContourSetFilter.cpp
  mitkSurfaceInterpolationController.cpp
)
