set(CPP_FILES
  Algorithms/mitkContourModelSource.cpp
  Algorithms/mitkContourModelSubDivisionFilter.cpp
  Algorithms/mitkContourModelToPointSetFilter.cpp
  Algorithms/mitkContourModelToSurfaceFilter.cpp
  Algorithms/mitkImageToContourModelFilter.cpp
  Algorithms/mitkContourObjectFactory.cpp
  DataManagement/mitkContourModel.cpp
  DataManagement/mitkContourElement.cpp
  Rendering/mitkContourModelGLMapper2D.cpp
  Rendering/mitkContourModelMapper2D.cpp
  Rendering/mitkContourModelMapper3D.cpp
  IO/mitkContourModelIOFactory.cpp
  IO/mitkContourModelReader.cpp
  IO/mitkContourModelWriter.cpp
  IO/mitkContourModelWriterFactory.cpp
)