SET(CPP_FILES
  DataHolder/mitkDataCollection.cpp
  DataHolder/mitkDataCollectionUtility.cpp
  ReaderWriter/mitkCollectionReader.cpp
  ReaderWriter/mitkCollectionWriter.cpp
  Utilities/mitkCostingStatistic.cpp
  Utilities/mitkCollectionStatistic.cpp
  Utilities/mitkDataCollectionUtilities.cpp
  testcase.cpp
)

SET(H_FILES
  DataHolder/mitkDataCollection.h
  DataHolder/mitkDataCollectionUtility.h
  ReaderWriter/mitkCollectionReader.h
  ReaderWriter/mitkCollectionWriter.h
  Iterators/mitkDataCollectionImageIterator.h
  Iterators/mitkDataCollectionSingleImageIterator.h
  Iterators/mitkDataCollectionVectorImageIterator.h
  Utilities/mitkCostingStatistic.h
  Utilities/mitkCollectionStatistic.h
  Utilities/mitkDataCollectionUtilities.h
  testcase.h
)
