set(CPP_FILES
  QmitkCustomWidgetOverlay.cpp
  QmitkOverlay.cpp
  QmitkOverlayContainerWidget.cpp
  QmitkOverlayController.cpp
  QmitkScalarBar.cpp
  QmitkScalarBarOverlay.cpp
  QmitkTextOverlay.cpp
)
