SET(MODULE_TESTS
  mitkDescriptivePharmacokineticBrixModelTest.cpp
  mitkStandardToftsModelTest.cpp
  mitkTwoCompartmentExchangeModelTest.cpp
  mitkExtendedToftsModelTest.cpp
  mitkConvertSignalToConcentrationTest.cpp
  mitkCurveDescriptiveParametersTest.cpp
  mitkOneTissueCompartmentModelTest.cpp
  mitkExtendedOneTissueCompartmentModelTest.cpp
  mitkTwoTissueCompartmentModelTest.cpp
  mitkTwoTissueCompartmentFDGModelTest.cpp
)
