SET(MODULE_TESTS
  mitkDescriptivePharmacokineticBrixModelTest.cpp
  mitkStandardToftsModelTest.cpp
  mitkTwoCompartmentExchangeModelTest.cpp
  mitkExtendedToftsModelTest.cpp
  mitkConvertSignalToConcentrationTest.cpp
  mitkCurveDescriptiveParametersTest.cpp
  mitkTwoStepLinearModelTest.cpp
  mitkThreeStepLinearModelTest.cpp
  mitkOneTissueCompartmentModelTest.cpp
)
