set(Plugin-Name "MITK MxN Multi Widget Editor")
set(Plugin-Version "1.0.0")
set(Plugin-Vendor "DKFZ, Division of Medical Image Computing")
set(Plugin-ContactAddress "http://www.mitk.org")
set(Require-Plugin org.mitk.gui.qt.common)