set(CPP_FILES
  Algorithms/mitkImageToPlanarFigureFilter.cpp
  Algorithms/mitkPlanarFigureObjectFactory.cpp
  Algorithms/mitkPlanarFigureSource.cpp
  Algorithms/mitkPlanarFigureToPlanarFigureFilter.cpp
  DataManagement/mitkPlanarAngle.cpp
  DataManagement/mitkPlanarCircle.cpp
  DataManagement/mitkPlanarEllipse.cpp
  DataManagement/mitkPlanarCross.cpp
  DataManagement/mitkPlanarFigure.cpp
  DataManagement/mitkPlanarFourPointAngle.cpp
  DataManagement/mitkPlanarLine.cpp
  DataManagement/mitkPlanarArrow.cpp
  DataManagement/mitkPlanarPolygon.cpp
  DataManagement/mitkPlanarSubdivisionPolygon.cpp
  DataManagement/mitkPlanarRectangle.cpp
  DataManagement/mitkPlanarFigureControlPointStyleProperty.cpp
  IO/mitkPlanarFigureIOFactory.cpp
  IO/mitkPlanarFigureReader.cpp
  IO/mitkPlanarFigureWriter.cpp
  IO/mitkPlanarFigureWriterFactory.cpp
  IO/mitkPlanarFigureSerializer.cpp
  IO/mitkPlanarFigureSubclassesSerializer.cpp
  Interactions/mitkPlanarFigureInteractor.cpp
  Rendering/mitkPlanarFigureMapper2D.cpp
)
