set(CPP_FILES
  QmitkRegistrationJob.cpp
  QmitkMappingJob.cpp
  QmitkFramesRegistrationJob.cpp
  QmitkAlgorithmProfileViewer.cpp
  QmitkAlgorithmSettingsConfig.cpp
  QmitkMAPAlgorithmModel.cpp
  QmitkAlgorithmListModel.cpp
  QmitkMapPropertyDelegate.cpp
  QmitkMapperSettingsWidget.cpp
  QmitkRegEvalSettingsWidget.cpp
  QmitkRegistrationManipulationWidget.cpp
)

set(UI_FILES
  src/QmitkAlgorithmProfileViewer.ui
  src/QmitkAlgorithmSettingsConfig.ui
  src/QmitkMapperSettingsWidget.ui
  src/QmitkRegEvalSettingsWidget.ui
  src/QmitkRegistrationManipulationWidget.ui
)
