set(CPP_FILES
  QmitkRegistrationJob.cpp
  QmitkMappingJob.cpp
  QmitkFramesRegistrationJob.cpp
  QmitkAlgorithmProfileViewer.cpp
  QmitkAlgorithmSettingsConfig.cpp
  QmitkMAPAlgorithmModel.cpp
  QmitkAlgorithmListModel.cpp
  QmitkMapPropertyDelegate.cpp
  QmitkMapperSettingsWidget.cpp
  QmitkRegEvalSettingsWidget.cpp
  QmitkRegistrationManipulationWidget.cpp
)

set(UI_FILES
  QmitkAlgorithmProfileViewer.ui
  QmitkAlgorithmSettingsConfig.ui
  QmitkMapperSettingsWidget.ui
  QmitkRegEvalSettingsWidget.ui
  QmitkRegistrationManipulationWidget.ui
)
