set(H_FILES
  include/QmitknnUNetEnsembleLayout.h
)

set(CPP_FILES
  QmitkSegWithPreviewToolGUIBase.cpp
  QmitkMultiLabelSegWithPreviewToolGUIBase.cpp
  QmitkBinaryThresholdToolGUIBase.cpp
  QmitkBinaryThresholdToolGUI.cpp
  QmitkBinaryThresholdULToolGUI.cpp
  QmitkConfirmSegmentationDialog.cpp
  QmitkCopyLabelToGroupDialog.cpp
  QmitkCopyToClipBoardDialog.cpp
  QmitkDrawPaintbrushToolGUI.cpp
  QmitkErasePaintbrushToolGUI.cpp
  QmitkEditableContourToolGUIBase.cpp
  QmitkGrowCutToolGUI.cpp
  QmitkLiveWireTool2DGUI.cpp
  QmitkLassoToolGUI.cpp
  QmitkOtsuTool3DGUI.cpp
  QmitkPaintbrushToolGUI.cpp
  QmitkPickingToolGUI.cpp
  QmitkSlicesInterpolator.cpp
  QmitkToolGUI.cpp
  QmitkToolGUIArea.cpp
  QmitkToolSelectionBox.cpp
  QmitknnUNetFolderParser.cpp
  QmitknnUNetToolGUI.cpp
  QmitknnUNetWorker.cpp
  QmitknnUNetGPU.cpp
  QmitkSurfaceStampWidget.cpp
  QmitkStaticDynamicSegmentationDialog.cpp
  QmitkSimpleLabelSetListWidget.cpp
  QmitkSegmentationTaskListWidget.cpp
  QmitkTotalSegmentatorToolGUI.cpp
  QmitkSetupVirtualEnvUtil.cpp
  QmitkMultiLabelInspector.cpp
  QmitkMultiLabelManager.cpp
  QmitkMultiLabelTreeModel.cpp
  QmitkMultiLabelTreeView.cpp
  QmitkMultiLabelPresetHelper.cpp
  QmitkMultiLabelSelectionButton.cpp
  QmitkMultiLabelSelectionLabel.cpp
  QmitkMultiLabelSelectionWidget.cpp
  QmitkFlatLabelInstanceProxyModel.cpp
  QmitkLabelColorItemDelegate.cpp
  QmitkLabelToggleItemDelegate.cpp
  QmitkFindSegmentationTaskDialog.cpp
  QmitkSegmentAnythingToolGUI.cpp
  QmitkMedSAMToolGUI.cpp
  QmitkMonaiLabelToolGUI.cpp
  QmitkMonaiLabel2DToolGUI.cpp
  QmitkMonaiLabel3DToolGUI.cpp
  QmitkLabelSelectionToolGUI.cpp
  SegmentationUtilities/QmitkBooleanOperationsWidget.cpp
  SegmentationUtilities/QmitkImageMaskingWidget.cpp
  SegmentationUtilities/QmitkMorphologicalOperationsWidget.cpp
  SegmentationUtilities/QmitkConvertToMultiLabelSegmentationWidget.cpp
  SegmentationUtilities/QmitkExtractFromMultiLabelSegmentationWidget.cpp
)

set(UI_FILES
  src/QmitkConfirmSegmentationDialog.ui
  src/QmitkCopyLabelToGroupDialog.ui
  src/QmitkGrowCutToolWidgetControls.ui
  src/QmitkOtsuToolWidgetControls.ui
  src/QmitkSurfaceStampWidgetGUIControls.ui
  src/QmitknnUNetToolGUIControls.ui
  src/QmitkEditableContourToolGUIControls.ui
  src/QmitkSegmentationTaskListWidget.ui
  src/QmitkTotalSegmentatorGUIControls.ui
  src/QmitkMultiLabelInspectorControls.ui
  src/QmitkMultiLabelManagerControls.ui
  src/QmitkMultiLabelSelectionLabel.ui
  src/QmitkMultiLabelSelectionWidget.ui
  src/QmitkFindSegmentationTaskDialog.ui
  src/QmitkSegmentAnythingGUIControls.ui
  src/QmitkMedSAMGUIControls.ui
  src/QmitkMonaiLabelToolGUIControls.ui
  src/QmitkLabelSelectionToolGUIControls.ui
  src/SegmentationUtilities/QmitkBooleanOperationsWidgetControls.ui
  src/SegmentationUtilities/QmitkImageMaskingWidgetControls.ui
  src/SegmentationUtilities/QmitkMorphologicalOperationsWidgetControls.ui
  src/SegmentationUtilities/QmitkConvertToMultiLabelSegmentationWidgetControls.ui
  src/SegmentationUtilities/QmitkExtractFromMultiLabelSegmentationWidgetControls.ui
)

set(QRC_FILES
  resources/SegmentationUI.qrc
)
