set( CPP_FILES
Qmitk/QmitkAdaptiveRegionGrowingToolGUI.cpp
Qmitk/QmitkBinaryThresholdToolGUI.cpp
Qmitk/QmitkBinaryThresholdULToolGUI.cpp
Qmitk/QmitkCalculateGrayValueStatisticsToolGUI.cpp
Qmitk/QmitkConfirmSegmentationDialog.cpp
Qmitk/QmitkCopyToClipBoardDialog.cpp
Qmitk/QmitkDrawPaintbrushToolGUI.cpp
Qmitk/QmitkErasePaintbrushToolGUI.cpp
Qmitk/QmitkFastMarchingTool3DGUI.cpp
Qmitk/QmitkFastMarchingToolGUI.cpp

Qmitk/QmitkLiveWireTool2DGUI.cpp
Qmitk/QmitkNewSegmentationDialog.cpp
Qmitk/QmitkOtsuTool3DGUI.cpp
Qmitk/QmitkPaintbrushToolGUI.cpp
Qmitk/QmitkPickingToolGUI.cpp
Qmitk/QmitkPixelManipulationToolGUI.cpp
Qmitk/QmitkSlicesInterpolator.cpp
Qmitk/QmitkToolGUI.cpp
Qmitk/QmitkToolGUIArea.cpp
Qmitk/QmitkToolReferenceDataSelectionBox.cpp
Qmitk/QmitkToolRoiDataSelectionBox.cpp
Qmitk/QmitkToolSelectionBox.cpp
Qmitk/QmitkToolWorkingDataSelectionBox.cpp
Qmitk/QmitkWatershedToolGUI.cpp
#Added from ML
Qmitk/QmitkLabelSetWidget.cpp
Qmitk/QmitkSurfaceStampWidget.cpp
Qmitk/QmitkMaskStampWidget.cpp
Qmitk/QmitkSliceBasedInterpolatorWidget.cpp
Qmitk/QmitkSurfaceBasedInterpolatorWidget.cpp
Qmitk/QmitkSearchLabelDialog.cpp
)

set(MOC_H_FILES
Qmitk/QmitkAdaptiveRegionGrowingToolGUI.h
Qmitk/QmitkBinaryThresholdToolGUI.h
Qmitk/QmitkBinaryThresholdULToolGUI.h
Qmitk/QmitkCalculateGrayValueStatisticsToolGUI.h
Qmitk/QmitkConfirmSegmentationDialog.h
Qmitk/QmitkCopyToClipBoardDialog.h
Qmitk/QmitkDrawPaintbrushToolGUI.h
Qmitk/QmitkErasePaintbrushToolGUI.h
Qmitk/QmitkFastMarchingTool3DGUI.h
Qmitk/QmitkFastMarchingToolGUI.h
Qmitk/QmitkLiveWireTool2DGUI.h
Qmitk/QmitkNewSegmentationDialog.h
Qmitk/QmitkOtsuTool3DGUI.h
Qmitk/QmitkPaintbrushToolGUI.h
Qmitk/QmitkPickingToolGUI.h
Qmitk/QmitkPixelManipulationToolGUI.h
Qmitk/QmitkSlicesInterpolator.h
Qmitk/QmitkToolGUI.h
Qmitk/QmitkToolGUIArea.h
Qmitk/QmitkToolReferenceDataSelectionBox.h
Qmitk/QmitkToolRoiDataSelectionBox.h
Qmitk/QmitkToolSelectionBox.h
Qmitk/QmitkToolWorkingDataSelectionBox.h
Qmitk/QmitkWatershedToolGUI.h
#Added from ML
Qmitk/QmitkLabelSetWidget.h
Qmitk/QmitkSurfaceStampWidget.h
Qmitk/QmitkMaskStampWidget.h
Qmitk/QmitkSliceBasedInterpolatorWidget.h
Qmitk/QmitkSurfaceBasedInterpolatorWidget.h
Qmitk/QmitkSearchLabelDialog.h
)

set(UI_FILES
Qmitk/QmitkAdaptiveRegionGrowingToolGUIControls.ui
Qmitk/QmitkConfirmSegmentationDialog.ui
Qmitk/QmitkOtsuToolWidgetControls.ui
Qmitk/QmitkPickingToolGUIControls.ui
Qmitk/QmitkLiveWireTool2DGUIControls.ui
#Added from ML
Qmitk/QmitkLabelSetWidgetControls.ui
Qmitk/QmitkSurfaceStampWidgetGUIControls.ui
Qmitk/QmitkMaskStampWidgetGUIControls.ui
Qmitk/QmitkSliceBasedInterpolatorWidgetGUIControls.ui
Qmitk/QmitkSurfaceBasedInterpolatorWidgetGUIControls.ui
Qmitk/QmitkSearchLabelDialogGUI.ui
)

set(QRC_FILES
  resources/SegmentationUI.qrc
)
