SET(CPP_FILES
  mitkAngleCorrectByPointFilter.cpp
  mitkAutoCropImageFilter.cpp
  mitkBaseDataSource.cpp
  mitkBaseProcess.cpp
  mitkBoundingObjectCutter.cpp
  mitkCalculateSegmentationVolume.cpp
  mitkCallbackFromGUIThread.cpp
  mitkContourSetToPointSetFilter.cpp
  mitkCoreObjectFactory.cpp
  mitkCylindricToCartesianFilter.cpp
  mitkDataTreeNodeFactory.cpp
  mitkDataTreeNodeSource.cpp
  mitkDiffImageApplier.cpp
  mitkDopplerToStrainRateFilter.cpp
  mitkExtractImageFilter.cpp
  mitkExtractDirectedPlaneImageFilter.cpp
  mitkGeometry2DDataToSurfaceFilter.cpp
  mitkGeometryClipImageFilter.cpp
  mitkGeometryDataSource.cpp
  mitkHistogramGenerator.cpp
  mitkImageCastPart1.cpp
  mitkImageCastPart2.cpp
  mitkImageChannelSelector.cpp
  mitkImageSliceSelector.cpp
  mitkImageSource.cpp
  mitkImageTimeSelector.cpp
  mitkImageToImageFilter.cpp
  mitkImageToLookupTableFilter.cpp
  mitkImageToSurfaceFilter.cpp
  mitkInterpolateLinesFilter.cpp
  #mitkItkProcessObjectAdapter.cpp
  mitkLabeledImageToSurfaceFilter.cpp
  mitkLookupTableSource.cpp
  mitkManualSegmentationToSurfaceFilter.cpp
  mitkMaskImageFilter.cpp
  mitkMeshSource.cpp
  mitkNonBlockingAlgorithm.cpp
  mitkOverwriteSliceImageFilter.cpp
  mitkPadImageFilter.cpp
  mitkPlaneCutFilter.cpp
  mitkPlaneFit.cpp
  mitkPlanesPerpendicularToLinesFilter.cpp
  mitkPointLocator.cpp
  mitkPointSetSource.cpp
  mitkPointSetToCurvedGeometryFilter.cpp
  mitkPointSetToGeometryDataFilter.cpp
  mitkPolygonToRingFilter.cpp
  mitkProbeFilter.cpp
  mitkSegmentationSink.cpp
  mitkShowSegmentationAsSurface.cpp
  mitkSubImageSelector.cpp
  mitkSurfaceSource.cpp
  mitkSurfaceToImageFilter.cpp
  mitkUIDGenerator.cpp
  mitkUnstructuredGridHistogram.cpp
  mitkUnstructuredGridSource.cpp
  mitkVolumeCalculator.cpp
  vtkPointSetSlicer.cxx
)
