SET(ALGORITHMS_CPP 
mitkAngleCorrectByPointFilter.cpp
mitkAutoCropImageFilter.cpp
mitkBaseDataSource.cpp
mitkBaseProcess.cpp
mitkBoundingObjectCutter.cpp
mitkCallbackFromGUIThread.cpp
mitkContourSetToPointSetFilter.cpp
# mitkCoonsPatchFilter.cpp
mitkCylindricToCartesianFilter.cpp
mitkDataTreeNodeFactory.cpp
mitkDataTreeNodeSource.cpp
# mitkDICOMFileIOFactory.cpp
# mitkDICOMFileReader.cpp
mitkDopplerToStrainRateFilter.cpp
mitkGeometry2DDataToSurfaceFilter.cpp
mitkGeometryClipImageFilter.cpp
mitkGeometryDataSource.cpp
mitkHistogramGenerator.cpp
mitkImageCastPart1.cpp
mitkImageCastPart2.cpp
mitkImageChannelSelector.cpp
mitkImageSliceSelector.cpp
mitkImageSource.cpp
mitkImageTimeSelector.cpp
mitkImageToImageFilter.cpp
mitkImageToLookupTableFilter.cpp
mitkImageToSurfaceFilter.cpp
mitkInterpolateLinesFilter.cpp
# mitkItkProcessObjectAdapter.cpp
mitkLookupTableSource.cpp
mitkManualSegmentationToSurfaceFilter.cpp
mitkMaskImageFilter.cpp
mitkMeshSource.cpp
mitkPadImageFilter.cpp
mitkPlaneCutFilter.cpp
mitkPlaneFit.cpp
mitkPlanesPerpendicularToLinesFilter.cpp
mitkPointSetSource.cpp
mitkPolygonToRingFilter.cpp
mitkProbeFilter.cpp
mitkSubImageSelector.cpp
mitkSurfaceSource.cpp
mitkSurfaceToImageFilter.cpp
mitkUIDGenerator.cpp
mitkVolumeCalculator.cpp
)

