/*=========================================================================

Program:   Medical Imaging & Interaction Toolkit
Language:  C++
Date:      $Date$
Version:   $Revision$

Copyright (c) German Cancer Research Center, Division of Medical and
Biological Informatics. All rights reserved.
See MITKCopyright.txt or http://www.mitk.org/copyright.html for details.

This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.

=========================================================================*/


#ifndef IMAGESLICESELECTOR_H_HEADER_INCLUDED_C1E4BE7B
#define IMAGESLICESELECTOR_H_HEADER_INCLUDED_C1E4BE7B

#include "mitkCommon.h"
#include "mitkSubImageSelector.h"

namespace mitk {

//##ModelId=3DCBFE35015D
//##Documentation
//## @brief Provides access to a slice of the input image
//##
//## If the input is generated by a ProcessObject, only the required data is
//## requested.
//## @ingroup Process
class ImageSliceSelector : public SubImageSelector
{
  public:
	  
	mitkClassMacro(ImageSliceSelector,SubImageSelector);

    itkNewMacro(Self);  

	itkGetConstMacro(SliceNr,int);
	itkSetMacro(SliceNr,int);

	itkGetConstMacro(TimeNr,int);
	itkSetMacro(TimeNr,int);

	itkGetConstMacro(ChannelNr,int);
	itkSetMacro(ChannelNr,int);

protected:
    //##ModelId=3E1A0A2E027F
    virtual void GenerateOutputInformation();

  virtual void GenerateInputRequestedRegion();

    //##ModelId=3E1A0A320090
    virtual void GenerateData();

	//##ModelId=3E1B196A0188
    ImageSliceSelector();

	//##ModelId=3E1B196A01C4
    virtual ~ImageSliceSelector();

    //##ModelId=3E1A0B390283
    int m_SliceNr;

    //##ModelId=3E1A0B57011E
    int m_TimeNr;

    //##ModelId=3E1A0B5A0281
    int m_ChannelNr;

//    ImageDataItem::Pointer m_CurrentSliceData;
};

} // namespace mitk



#endif /* IMAGESLICESELECTOR_H_HEADER_INCLUDED_C1E4BE7B */
