set(CPP_FILES
  mitkImageStatisticsCalculator.cpp
  mitkPointSetStatisticsCalculator.cpp
  mitkPointSetDifferenceStatisticsCalculator.cpp
  mitkIntensityProfile.cpp
  mitkHotspotMaskGenerator.cpp
  mitkMaskGenerator.cpp
  mitkPlanarFigureMaskGenerator.cpp
  mitkMultiLabelMaskGenerator.cpp
  mitkImageMaskGenerator.cpp
  mitkHistogramStatisticsCalculator.cpp
  mitkMaskUtilities.cpp
  mitkIgnorePixelMaskGenerator.cpp
)

set(H_FILES
  mitkImageStatisticsCalculator.h
  mitkPointSetDifferenceStatisticsCalculator.h
  mitkPointSetStatisticsCalculator.h
  mitkExtendedStatisticsImageFilter.h
  mitkExtendedLabelStatisticsImageFilter.h
  mitkHotspotMaskGenerator.h
  mitkMaskGenerator.h
  mitkPlanarFigureMaskGenerator.h
  mitkMultiLabelMaskGenerator.h
  mitkImageMaskGenerator.h
  mitkHistogramStatisticsCalculator.h
  mitkMaskUtilities.h
  mitkitkMaskImageFilter.h
  mitkIgnorePixelMaskGenerator.h
  mitkMinMaxImageFilterWithIndex.h
  mitkMinMaxLabelmageFilterWithIndex.h
)
