set(H_FILES
  itkMultiGaussianImageSource.h
  mitkHotspotMaskGenerator.h
  mitkLabelStatisticsImageFilter.h
  mitkMaskUtilities.h
  mitkMinMaxImageFilterWithIndex.h
  mitkMinMaxLabelmageFilterWithIndex.h
  mitkStatisticsImageFilter.h
  mitkitkMaskImageFilter.h
)

set(CPP_FILES
  mitkImageStatisticsCalculator.cpp
  mitkImageStatisticsContainer.cpp
  mitkPointSetStatisticsCalculator.cpp
  mitkPointSetDifferenceStatisticsCalculator.cpp
  mitkIntensityProfile.cpp
  #See T30375
  #mitkHotspotMaskGenerator.cpp
  mitkMaskGenerator.cpp
  mitkPlanarFigureMaskGenerator.cpp
  mitkMultiLabelMaskGenerator.cpp
  mitkImageMaskGenerator.cpp
  mitkHistogramStatisticsCalculator.cpp
  mitkIgnorePixelMaskGenerator.cpp
  mitkImageStatisticsPredicateHelper.cpp
  mitkImageStatisticsContainerNodeHelper.cpp
  mitkImageStatisticsContainerManager.cpp
  mitkStatisticsToImageRelationRule.cpp
  mitkStatisticsToMaskRelationRule.cpp
  mitkImageStatisticsConstants.cpp
)
