set(H_FILES
  include/itkMultiGaussianImageSource.h
  include/mitkHotspotMaskGenerator.h
  include/mitkLabelStatisticsImageFilter.h
  include/mitkMaskUtilities.h
  include/mitkMinMaxImageFilterWithIndex.h
  include/mitkMinMaxLabelmageFilterWithIndex.h
  include/mitkStatisticsImageFilter.h
  include/mitkitkMaskImageFilter.h
)

set(CPP_FILES
  mitkImageStatisticsCalculator.cpp
  mitkImageStatisticsContainer.cpp
  mitkPointSetStatisticsCalculator.cpp
  mitkPointSetDifferenceStatisticsCalculator.cpp
  mitkIntensityProfile.cpp
  #See T30375
  #mitkHotspotMaskGenerator.cpp
  mitkMaskGenerator.cpp
  mitkPlanarFigureMaskGenerator.cpp
  mitkMultiLabelMaskGenerator.cpp
  mitkImageMaskGenerator.cpp
  mitkHistogramStatisticsCalculator.cpp
  mitkIgnorePixelMaskGenerator.cpp
  mitkImageStatisticsPredicateHelper.cpp
  mitkImageStatisticsContainerNodeHelper.cpp
  mitkImageStatisticsContainerManager.cpp
  mitkStatisticsToImageRelationRule.cpp
  mitkStatisticsToMaskRelationRule.cpp
  mitkImageStatisticsConstants.cpp
)
