SET(Plugin-Name "MAP MITK Core Helper")
SET(Plugin-Version "0.1")
set(Plugin-Vendor "German Cancer Research Center (DKFZ)")
set(Plugin-ContactAddress "http://www.mitk.org")
set(Require-Plugin org.mitk.gui.common)
set(Plugin-ActivationPolicy eager)
