set(Plugin-Name "MatchPoint Algorithm Control")
set(Plugin-Version "0.2")
set(Plugin-Vendor "German Cancer Research Center (DKFZ)")
set(Plugin-ContactAddress "https://www.mitk.org")
set(Require-Plugin org.mitk.gui.qt.common org.mitk.gui.qt.datamanager org.mitk.matchpoint.core.helper)
