set(Plugin-Name "MITK-ToF Util")
set(Plugin-Version "0.1")
set(Plugin-Vendor "German Cancer Research Center (DKFZ)")
set(Plugin-ContactAddress "www.mitk.org/wiki/MITK-ToF")
set(Require-Plugin org.mitk.gui.qt.common)
