set(Plugin-Name "MITK-ToF Util")
set(Plugin-Version "0.1")
set(Plugin-Vendor "DKFZ, Medical and Biological Informatics")
set(Plugin-ContactAddress "www.mitk.org/wiki/MITK-ToF")
set(Require-Plugin org.mitk.gui.qt.common)