set (H_FILES
  DataStructure/mitkUndirectedGraph.h
  DataStructure/mitkUndirectedGraph.txx
  DataStructure/mitkCircularProfileTubeElement.h
  DataStructure/mitkTubeElement.h
  DataStructure/mitkTubeGraph.h
  DataStructure/mitkTubeGraphEdge.h
  DataStructure/mitkTubeGraphVertex.h
  Interactions/mitkTubeGraphDataInteractor.h
  Interactions/mitkTubeGraphPicker.h
  IO/mitkTubeGraphDefinitions.h
  IO/mitkTubeGraphIO.h
  IO/mitkTubeGraphObjectFactory.h
  Rendering/mitkTubeGraphProperty.h
  Rendering/mitkTubeGraphVtkMapper3D.h
)
set(CPP_FILES
  DataStructure/mitkCircularProfileTubeElement.cpp
  DataStructure/mitkTubeGraph.cpp
  DataStructure/mitkTubeGraphEdge.cpp
  DataStructure/mitkTubeGraphVertex.cpp
  Interactions/mitkTubeGraphDataInteractor.cpp
  Interactions/mitkTubeGraphPicker.cpp
  IO/mitkTubeGraphDefinitions.cpp
  IO/mitkTubeGraphIO.cpp
  IO/mitkTubeGraphModuleActivator.cpp
  IO/mitkTubeGraphObjectFactory.cpp
  Rendering/mitkTubeGraphProperty.cpp
  Rendering/mitkTubeGraphVtkMapper3D.cpp
)
set(RESOURCE_FILES
 Interactions/TubeGraphConfig.xml
 Interactions/TubeGraphInteraction.xml
)
