set (H_FILES
  #Algorithms/mitkTubeGraphConverter.h
  DataStructure/mitkUndirectedGraph.h
  DataStructure/mitkUndirectedGraph.txx
  DataStructure/mitkCircularProfileTubeElement.h
  DataStructure/mitkTubeElement.h
  DataStructure/mitkTubeGraph.h
  DataStructure/mitkTubeGraphEdge.h
  DataStructure/mitkTubeGraphVertex.h
  #Interactions/mitkTubeGraphInteractor.h
  Interactions/mitkTubeGraphDataInteractor.h
  Interactions/mitkTubeGraphPicker.h
  IODataStructures/mitkTubeGraphDefinitions.h
  IODataStructures/mitkTubeGraphIOFactory.h
  IODataStructures/mitkTubeGraphObjectFactory.h
  IODataStructures/mitkTubeGraphReader.h
  IODataStructures/mitkTubeGraphSerializer.h
  IODataStructures/mitkTubeGraphWriter.h
  IODataStructures/mitkTubeGraphWriterFactory.h
  Rendering/mitkTubeGraphGeometry3D.h
  Rendering/mitkTubeGraphProperty.h
  Rendering/mitkTubeGraphVtkMapper3D.h
)
set(CPP_FILES
  #Algorithms/mitkTubeGraphConverter.cpp
  DataStructure/mitkCircularProfileTubeElement.cpp
  DataStructure/mitkTubeGraph.cpp
  DataStructure/mitkTubeGraphEdge.cpp
  DataStructure/mitkTubeGraphVertex.cpp
  #Interactions/mitkTubeGraphInteractor.cpp
  Interactions/mitkTubeGraphDataInteractor.cpp
  Interactions/mitkTubeGraphPicker.cpp
  IODataStructures/mitkTubeGraphDefinitions.cpp
  IODataStructures/mitkTubeGraphIOFactory.cpp
  IODataStructures/mitkTubeGraphObjectFactory.cpp
  IODataStructures/mitkTubeGraphReader.cpp
  IODataStructures/mitkTubeGraphSerializer.cpp
  IODataStructures/mitkTubeGraphWriter.cpp
  IODataStructures/mitkTubeGraphWriterFactory.cpp
  Rendering/mitkTubeGraphGeometry3D.cpp
  Rendering/mitkTubeGraphProperty.cpp
  Rendering/mitkTubeGraphVtkMapper3D.cpp
)
set(RESOURCE_FILES
 Interactions/TubeGraphConfig.xml
 Interactions/TubeGraphInteraction.xml
)
