set(H_FILES
  itkStitchImageFilter.h
  mitkMatchPointPropertyTags.h
)

set(CPP_FILES
  mitkMAPRegistrationWrapper.cpp
  mitkMAPRegistrationWrapperObjectFactory.cpp
  mitkRegEvaluationObjectFactory.cpp
  mitkRegEvaluationObject.cpp
  Helper/mitkUIDHelper.cpp
  Helper/mitkMAPAlgorithmHelper.cpp
  Helper/mitkMaskedAlgorithmHelper.cpp
  Helper/mitkRegistrationHelper.cpp
  Helper/mitkImageMappingHelper.cpp
  Helper/mitkMultiLabelSegmentationMappingHelper.cpp
  Helper/mitkImageStitchingHelper.cpp
  Helper/mitkPointSetMappingHelper.cpp
  Helper/mitkResultNodeGenerationHelper.cpp
  Helper/mitkTimeFramesRegistrationHelper.cpp
  Rendering/mitkRegistrationWrapperMapper2D.cpp
  Rendering/mitkRegistrationWrapperMapper3D.cpp
  Rendering/mitkRegistrationWrapperMapperBase.cpp
  Rendering/mitkRegEvaluationMapper2D.cpp
  Rendering/mitkRegVisStyleProperty.cpp
  Rendering/mitkRegVisDirectionProperty.cpp
  Rendering/mitkRegVisColorStyleProperty.cpp
  Rendering/mitkRegVisPropertyTags.cpp
  Rendering/mitkRegVisHelper.cpp
  Rendering/mitkRegEvalStyleProperty.cpp
  Rendering/mitkRegEvalWipeStyleProperty.cpp
)
