language: cpp
compiler:
  - gcc
  - clang
env:
  matrix:
  - BUILD_CONFIGURATION=0
  - BUILD_CONFIGURATION=1
  - BUILD_CONFIGURATION=2
  - BUILD_CONFIGURATION=3
  - BUILD_CONFIGURATION=4
  - BUILD_CONFIGURATION=5
  - BUILD_CONFIGURATION=6
  - BUILD_CONFIGURATION=7

branches:
  only:
    - master
    - development
    - /^release-.*$/

script:
  - ctest -VV -S ./cmake/usCTestScript_travis.cmake

