FIND_PACKAGE(ITK REQUIRED)
#
# for some reason this does not work on windows, probably an ITK bug
# ITK_BUILD_SHARED is OFF even in shared library builds
#
#IF(ITK_FOUND AND NOT ITK_BUILD_SHARED)
#  MESSAGE(FATAL_ERROR "MITK only supports a ITK which was built with shared libraries. Turn on BUILD_SHARED_LIBS in your ITK config.")
#ENDIF(ITK_FOUND AND NOT ITK_BUILD_SHARED)

INCLUDE(${ITK_USE_FILE})
LIST(APPEND ALL_LIBRARIES ${ITK_LIBRARIES})
LIST(APPEND ALL_INCLUDE_DIRECTORIES ${ITK_INCLUDE_DIRS})
IF(ITK_USE_SYSTEM_GDCM)
  FIND_PACKAGE(GDCM PATHS ${ITK_GDCM_DIR} REQUIRED)
  LIST(APPEND ALL_LIBRARIES ${GDCM_LIBRARIES})
ENDIF(ITK_USE_SYSTEM_GDCM)


