if(TARGET itksys)
  set(ITK_TARGETS_IMPORTED 1)
endif()

find_package(ITK REQUIRED)
find_package(GDCM PATHS ${ITK_GDCM_DIR} REQUIRED)

list(APPEND ALL_INCLUDE_DIRECTORIES ${GDCM_INCLUDE_DIRS})
list(APPEND ALL_LIBRARIES ${GDCM_LIBRARIES})
list(APPEND ALL_LIBRARY_DIRS ${GDCM_LIBRARY_DIRS})
