if(NOT EXISTS "${YAML_CPP_INCLUDE_DIR}" AND "${YAML_CPP_INCLUDE_DIR}" MATCHES ".*/\.\./include")
  string(REPLACE /../i /i YAML_CPP_INCLUDE_DIR "${YAML_CPP_INCLUDE_DIR}")
endif()
if("${YAML_CPP_INCLUDE_DIR}" MATCHES "/usr/.*/include")
  unset(YAML_CPP_INCLUDE_DIR) # gcc don't work whith -isystem /usr/include
endif()
list(APPEND ALL_LIBRARIES ${YAML_CPP_LIBRARIES})
if(YAML_CPP_INCLUDE_DIR)
  list(APPEND ALL_INCLUDE_DIRECTORIES ${YAML_CPP_INCLUDE_DIR})
endif()
