IF(MITK_USE_Boost)

  IF(NOT MITK_USE_SYSTEM_Boost)
    SET(Boost_NO_SYSTEM_PATHS 1)
  ENDIF()
  
  SET(Boost_USE_MULTITHREADED 1)
  SET(Boost_USE_STATIC_LIBS 0)
  SET(Boost_USE_STATIC_RUNTIME 0)

  IF(MITK_USE_Boost_LIBRARIES)
    FIND_PACKAGE(Boost 1.40.0 REQUIRED COMPONENTS ${MITK_USE_Boost_LIBRARIES})
  ELSE()
    FIND_PACKAGE(Boost 1.40.0 REQUIRED)
  ENDIF()

  LIST(APPEND ALL_INCLUDE_DIRECTORIES ${Boost_INCLUDE_DIRS})
  IF(Boost_LIBRARIES)
    LIST(APPEND ALL_LIBRARIES ${Boost_LIBRARIES})
    LINK_DIRECTORIES(${Boost_LIBRARY_DIRS})
  ENDIF()

ENDIF(MITK_USE_Boost)

