if(TBB_REQUIRED_COMPONENTS_BY_MODULE)
  foreach(tbb_component ${TBB_REQUIRED_COMPONENTS_BY_MODULE})
    if(NOT tbb_component MATCHES "^tbb")
      set(tbb_component "tbb${tbb_component}")
    endif()
    list(APPEND ALL_LIBRARIES "TBB::${tbb_component}")
  endforeach()
else()
  set(ALL_LIBRARIES "TBB::tbb")
endif()
