if(TARGET itksys)
  set(ITK_TARGETS_IMPORTED 1)
endif()

find_package(ITK COMPONENTS ${ITK_REQUIRED_COMPONENTS_BY_MODULE} REQUIRED)

if(NOT _mitk_itk_config_parsed)
  if(NOT DEFINED ITK_NO_IO_FACTORY_REGISTER_MANAGER)
    set(ITK_NO_IO_FACTORY_REGISTER_MANAGER 1)
  endif()
  include(${ITK_USE_FILE})
endif()

list(APPEND ALL_LIBRARIES ${ITK_LIBRARIES})
list(APPEND ALL_INCLUDE_DIRECTORIES ${ITK_INCLUDE_DIRS})

set(_mitk_itk_config_parsed 1)
