if( NOT WIN32 AND NOT APPLE )
  set(MISSING_LIBS_REQUIRED_BY_DCMTK wrap tiff z)
endif( NOT WIN32 AND NOT APPLE )

set(QT_USE_QTSQL 1)

list(APPEND ALL_INCLUDE_DIRECTORIES ${DCMTK_INCLUDE_DIR})
list(APPEND ALL_LIBRARIES ${DCMTK_LIBRARIES} ${MISSING_LIBS_REQUIRED_BY_DCMTK})
