list(APPEND ALL_INCLUDE_DIRECTORIES ${DCMQI_INCLUDE_DIR})
list(APPEND ALL_LIBRARIES ${DCMQI_LIBRARY})
message("Config DCMQI_INCLUDE_DIR: ${DCMQI_INCLUDE_DIR}")
message("Config DCMQI_LIBRARY: ${DCMQI_LIBRARY}")
