# MESSAGE("In package CTK config")
FIND_PACKAGE(CTK REQUIRED)
LIST(APPEND ALL_INCLUDE_DIRECTORIES ${CTK_INCLUDE_DIRS})
LIST(APPEND ALL_LIBRARIES ${CTK_LIBRARIES})
link_directories(${CTK_LIBRARY_DIRS})

 
