find_package(Qt5 COMPONENTS ${Qt5_REQUIRED_COMPONENTS_BY_MODULE} REQUIRED QUIET)
foreach(_component ${Qt5_REQUIRED_COMPONENTS_BY_MODULE})
  list(APPEND ALL_LIBRARIES ${Qt5${_component}_LIBRARIES})
endforeach()
