SET( VPX_LIB "" CACHE FILEPATH "Search for the vpx library file" )
SET( VPX_HEADER_DIR "" CACHE PATH "The path containing vpy headers" )
SET( VPX_FOUND FALSE )

IF(VPX_LIB AND VPX_HEADER_DIR)
  LIST(APPEND ALL_LIBRARIES ${VPX_LIB})
  LIST(APPEND ALL_INCLUDE_DIRECTORIES ${VPX_HEADER_DIR})
  SET( VPX_FOUND TRUE )
ENDIF()
