set(CPP_FILES
  mitkSimulation.cpp
  mitkSimulationDrawTool.cpp
  mitkSimulationPropAssemblyVisitor.cpp
  mitkSimulationIOFactory.cpp
  mitkSimulationMapper3D.cpp
  mitkSimulationReader.cpp
  mitkSimulationObjectFactory.cpp
  mitkSimulationModel.cpp
)
