set(CPP_FILES
  mitkGetSimulationService.cpp
  mitkIndexROI.cpp
  mitkISimulationService.cpp
  mitkSetVtkRendererVisitor.cpp
  mitkSimulation.cpp
  mitkSimulationActivator.cpp
  mitkSimulationIOFactory.cpp
  mitkSimulationObjectFactory.cpp
  mitkSimulationReader.cpp
  mitkSimulationService.cpp
  mitkSimulationVtkMapper3D.cpp
  mitkVtkModel.cpp
  mitkVtkSimulationPolyDataMapper.cpp
)
