set(H_FILES
  include/itkCoocurenceMatrixFeatureFunctor.h
  include/itkEnhancedHistogramToNeighbourhoodGreyLevelDifferenceFeaturesFilter.h
  include/itkEnhancedHistogramToRunLengthFeaturesFilter.h
  include/itkEnhancedHistogramToSizeZoneFeaturesFilter.h
  include/itkEnhancedHistogramToTextureFeaturesFilter.h
  include/itkEnhancedScalarImageToNeighbourhoodGreyLevelDifferenceFeaturesFilter.h
  include/itkEnhancedScalarImageToNeighbourhoodGreyLevelDifferenceMatrixFilter.h
  include/itkEnhancedScalarImageToRunLengthFeaturesFilter.h
  include/itkEnhancedScalarImageToRunLengthMatrixFilter.h
  include/itkEnhancedScalarImageToSizeZoneFeaturesFilter.h
  include/itkEnhancedScalarImageToSizeZoneMatrixFilter.h
  include/itkEnhancedScalarImageToTextureFeaturesFilter.h
  include/itkFirstOrderStatisticsFeatureFunctor.h
  include/itkLocalIntensityFilter.h
  include/itkLocalStatisticFilter.h
  include/itkMultiHistogramFilter.h
)

set(CPP_FILES
  mitkCLResultWriter.cpp
  mitkCLResultXMLWriter.cpp

  Algorithms/itkLabelSampler.cpp
  Algorithms/itkSmoothedClassProbabilites.cpp
  Algorithms/mitkRandomImageSampler.cpp

  Features/itkNeighborhoodFunctorImageFilter.cpp
  Features/itkLineHistogramBasedMassImageFilter.cpp

  GlobalImageFeatures/mitkGIFCooccurenceMatrix.cpp
  GlobalImageFeatures/mitkGIFCooccurenceMatrix2.cpp
  GlobalImageFeatures/mitkGIFGreyLevelRunLength.cpp
  GlobalImageFeatures/mitkGIFImageDescriptionFeatures.cpp
  GlobalImageFeatures/mitkGIFFirstOrderStatistics.cpp
  GlobalImageFeatures/mitkGIFFirstOrderHistogramStatistics.cpp
  GlobalImageFeatures/mitkGIFFirstOrderNumericStatistics.cpp
  GlobalImageFeatures/mitkGIFVolumetricStatistics.cpp
  GlobalImageFeatures/mitkGIFNeighbouringGreyLevelDependenceFeatures.cpp
  GlobalImageFeatures/mitkGIFNeighbourhoodGreyLevelDifference.cpp
  GlobalImageFeatures/mitkGIFGreyLevelSizeZone.cpp
  GlobalImageFeatures/mitkGIFGreyLevelDistanceZone.cpp
  GlobalImageFeatures/mitkGIFLocalIntensity.cpp
  GlobalImageFeatures/mitkGIFVolumetricDensityStatistics.cpp
  GlobalImageFeatures/mitkGIFIntensityVolumeHistogramFeatures.cpp
  GlobalImageFeatures/mitkGIFNeighbourhoodGreyToneDifferenceFeatures.cpp
  GlobalImageFeatures/mitkGIFCurvatureStatistic.cpp

  MiniAppUtils/mitkGlobalImageFeaturesParameter.cpp
  MiniAppUtils/mitkSplitParameterToVector.cpp

  mitkCLUtil.cpp

)

set( TOOL_FILES
)
