set(H_FILES
  itkCoocurenceMatrixFeatureFunctor.h
  itkEnhancedHistogramToNeighbourhoodGreyLevelDifferenceFeaturesFilter.h
  itkEnhancedHistogramToRunLengthFeaturesFilter.h
  itkEnhancedHistogramToSizeZoneFeaturesFilter.h
  itkEnhancedHistogramToTextureFeaturesFilter.h
  itkEnhancedScalarImageToNeighbourhoodGreyLevelDifferenceFeaturesFilter.h
  itkEnhancedScalarImageToNeighbourhoodGreyLevelDifferenceMatrixFilter.h
  itkEnhancedScalarImageToRunLengthFeaturesFilter.h
  itkEnhancedScalarImageToRunLengthMatrixFilter.h
  itkEnhancedScalarImageToSizeZoneFeaturesFilter.h
  itkEnhancedScalarImageToSizeZoneMatrixFilter.h
  itkEnhancedScalarImageToTextureFeaturesFilter.h
  itkFirstOrderStatisticsFeatureFunctor.h
  itkLocalIntensityFilter.h
  itkLocalStatisticFilter.h
  itkMultiHistogramFilter.h
)

set(CPP_FILES
  mitkCLResultWriter.cpp
  mitkCLResultXMLWriter.cpp

  Algorithms/itkLabelSampler.cpp
  Algorithms/itkSmoothedClassProbabilites.cpp
  Algorithms/mitkRandomImageSampler.cpp

  Features/itkNeighborhoodFunctorImageFilter.cpp
  Features/itkLineHistogramBasedMassImageFilter.cpp

  GlobalImageFeatures/mitkGIFCooccurenceMatrix.cpp
  GlobalImageFeatures/mitkGIFCooccurenceMatrix2.cpp
  GlobalImageFeatures/mitkGIFGreyLevelRunLength.cpp
  GlobalImageFeatures/mitkGIFImageDescriptionFeatures.cpp
  GlobalImageFeatures/mitkGIFFirstOrderStatistics.cpp
  GlobalImageFeatures/mitkGIFFirstOrderHistogramStatistics.cpp
  GlobalImageFeatures/mitkGIFFirstOrderNumericStatistics.cpp
  GlobalImageFeatures/mitkGIFVolumetricStatistics.cpp
  GlobalImageFeatures/mitkGIFNeighbouringGreyLevelDependenceFeatures.cpp
  GlobalImageFeatures/mitkGIFNeighbourhoodGreyLevelDifference.cpp
  GlobalImageFeatures/mitkGIFGreyLevelSizeZone.cpp
  GlobalImageFeatures/mitkGIFGreyLevelDistanceZone.cpp
  GlobalImageFeatures/mitkGIFLocalIntensity.cpp
  GlobalImageFeatures/mitkGIFVolumetricDensityStatistics.cpp
  GlobalImageFeatures/mitkGIFIntensityVolumeHistogramFeatures.cpp
  GlobalImageFeatures/mitkGIFNeighbourhoodGreyToneDifferenceFeatures.cpp
  GlobalImageFeatures/mitkGIFCurvatureStatistic.cpp

  MiniAppUtils/mitkGlobalImageFeaturesParameter.cpp
  MiniAppUtils/mitkSplitParameterToVector.cpp

  mitkCLUtil.cpp
)
