SET(CPP_FILES
  mitkAction.cpp
  mitkAddContourTool.cpp
  mitkAffineInteractor.cpp
  mitkAutoCropTool.cpp
  mitkAutoSegmentationTool.cpp
  mitkBinaryThresholdTool.cpp
  mitkCalculateVolumetryTool.cpp
  mitkCalculateGrayValueStatisticsTool.cpp
  mitkConferenceEventMapper.cpp
  mitkConnectPointsInteractor.cpp
  mitkContourInteractor.cpp
  mitkContourTool.cpp
  mitkCoordinateSupplier.cpp
  mitkCorrectorTool2D.cpp
  mitkCreateSurfaceTool.cpp
  mitkDisplayCoordinateOperation.cpp
  mitkDisplayInteractor.cpp
  mitkDisplayPointSetInteractor.cpp
  mitkDisplayPositionEvent.cpp
  mitkDisplayVectorInteractor.cpp
  mitkEraseRegionTool.cpp
  mitkEvent.cpp
  mitkEventDescription.cpp
  mitkEventMapper.cpp
  mitkExtrudedContourInteractor.cpp
  mitkFeedbackContourTool.cpp
  mitkFillRegionTool.cpp
  mitkGlobalInteraction.cpp
  mitkHierarchicalInteractor.cpp
  # mitkInteractionDebug.cpp
  mitkInteractionDebugger.cpp
  mitkInteractor.cpp
  mitkLineInteractor.cpp
  mitkPointInteractor.cpp
  mitkPointSetInteractor.cpp
  mitkPointSnapInteractor.cpp
  mitkPolygonInteractor.cpp
  mitkPositionEvent.cpp
  mitkPositionTracker.cpp
  mitkPrimStripInteractor.cpp
  mitkRegionGrowingTool.cpp
  mitkSeedsInteractor.cpp
  mitkSegmentationsProcessingTool.cpp
  mitkSegTool2D.cpp
  mitkSetRegionTool.cpp
  mitkSocketClient.cpp
  mitkState.cpp
  mitkStateEvent.cpp
  mitkStateMachine.cpp
  mitkStateMachineFactory.cpp
  mitkSubstractContourTool.cpp
  mitkTool.cpp
  mitkTransition.cpp
)
