SET(CPP_FILES
  mitkAction.cpp
  mitkTool.cpp
  mitkAddContourTool.cpp
  mitkContourTool.cpp
  mitkCorrectorTool2D.cpp
  mitkRegionGrowingTool.cpp
  mitkSegTool2D.cpp
  mitkSegTool3D.cpp
  mitkSetRegionTool.cpp
  mitkFillRegionTool.cpp
  mitkEraseRegionTool.cpp
  mitkSubstractContourTool.cpp
  mitkAddContourToolFactory.cpp
  mitkCorrectorTool2DFactory.cpp
  mitkRegionGrowingToolFactory.cpp
  mitkSubstractContourToolFactory.cpp
  mitkFillRegionToolFactory.cpp
  mitkEraseRegionToolFactory.cpp
  mitkAffineInteractor.cpp
  mitkConferenceEventMapper.cpp
  mitkConnectPointsInteractor.cpp
  mitkContourInteractor.cpp
  mitkCoordinateSupplier.cpp
  mitkDisplayCoordinateOperation.cpp
  mitkDisplayInteractor.cpp
  mitkDisplayPositionEvent.cpp
  mitkDisplayVectorInteractor.cpp
  mitkEvent.cpp
  mitkEventDescription.cpp
  mitkEventMapper.cpp
  mitkExtrudedContourInteractor.cpp
  mitkGlobalInteraction.cpp
  mitkHierarchicalInteractor.cpp
  # mitkInteractionDebug.cpp
  mitkInteractionDebugger.cpp
  mitkInteractor.cpp
  mitkLineInteractor.cpp
  mitkPointInteractor.cpp
  mitkPointSetInteractor.cpp
  mitkPointSnapInteractor.cpp
  mitkPolygonInteractor.cpp
  mitkPositionEvent.cpp
  mitkPositionTracker.cpp
  mitkPrimStripInteractor.cpp
  mitkSeedsInteractor.cpp
  mitkState.cpp
  mitkStateEvent.cpp
  mitkStateMachine.cpp
  mitkStateMachineFactory.cpp
  mitkTransition.cpp
)
