set(SRC_CPP_FILES
  @PLUGIN_SOURCES@
)

set(INTERNAL_CPP_FILES
  @PLUGIN_INTERNAL_SOURCES@
)

set(UI_FILES
  @PLUGIN_UI_FILES@
)

set(MOC_H_FILES
  @PLUGIN_MOC_H_FILES@
)

set(RESOURCE_FILES
  @PLUGIN_RESOURCE_FILES@
)

set(RES_FILES
  @PLUGIN_RES_FILES@
)

@SET_MANIFEST_SRC@

foreach(file ${SRC_CPP_FILES})
  set(CPP_FILES ${CPP_FILES} src/${file})
endforeach(file ${SRC_CPP_FILES})

foreach(file ${INTERNAL_CPP_FILES})
  set(CPP_FILES ${CPP_FILES} src/internal/${file})
endforeach(file ${INTERNAL_CPP_FILES})

