set(Plugin-Name "MITK Job Plug-in")
set(Plugin-Version "0.1")
set(Plugin-Vendor "German Cancer Research Center (DKFZ)")
set(Plugin-ContactAddress "https://www.mitk.org")
set(Require-Plugin org.blueberry.core.jobs)
