set(MODULE_TESTS
  mitkSUVCalculationTest.cpp
  mitkSUVCalculationHelperTest.cpp
  mitkSUVFunctorPolicyTest.cpp
  mitkSUVImageFilterTest.cpp
  mitkSUVInputModelTest.cpp
  mitkSUVNormalizationStrategyTest.cpp
  mitkPETIBSIBenchmarkTest.cpp
  mitkPETPrivateTagLiftTest.cpp
)
