set(CPP_FILES
  QmitkParameterFitBackgroundJob.cpp
  QmitkSimpleBarrierParametersDelegate.cpp
  QmitkSimpleBarrierTypeDelegate.cpp
  QmitkSimpleBarrierModel.cpp
  QmitkSimpleBarrierManagerWidget.cpp
  QmitkInitialValuesModel.cpp
  QmitkInitialValuesManagerWidget.cpp
  QmitkInitialValuesDelegate.cpp
  QmitkInitialValuesTypeDelegate.cpp
  QmitkFitParameterModel.cpp
  QmitkFitParameterWidget.cpp
  QmitkInspectionPositionWidget.cpp
  QmitkFitPlotDataWidget.cpp
  QmitkFitPlotDataModel.cpp
)

set(UI_FILES
  QmitkSimpleBarrierManagerWidget.ui
  QmitkInitialValuesManagerWidget.ui
  QmitkFitParameterWidget.ui
  QmitkInspectionPositionWidget.ui
  QmitkFitPlotDataWidget.ui
)
