set(CPP_FILES
  Qmitk/QmitkParameterFitBackgroundJob.cpp
  Qmitk/QmitkSimpleBarrierParametersDelegate.cpp
  Qmitk/QmitkSimpleBarrierTypeDelegate.cpp
  Qmitk/QmitkSimpleBarrierModel.cpp
  Qmitk/QmitkSimpleBarrierManagerWidget.cpp
  Qmitk/QmitkInitialValuesModel.cpp
  Qmitk/QmitkInitialValuesManagerWidget.cpp
  Qmitk/QmitkInitialValuesDelegate.cpp
  Qmitk/QmitkInitialValuesTypeDelegate.cpp
  Qmitk/QmitkFitParameterModel.cpp
  Qmitk/QmitkFitParameterWidget.cpp
  Qmitk/QmitkInspectionPositionWidget.cpp
  Qmitk/QmitkFitPlotDataWidget.cpp
  Qmitk/QmitkFitPlotDataModel.cpp
)

set(UI_FILES
  src/Qmitk/QmitkSimpleBarrierManagerWidget.ui
  src/Qmitk/QmitkInitialValuesManagerWidget.ui
  src/Qmitk/QmitkFitParameterWidget.ui
  src/Qmitk/QmitkInspectionPositionWidget.ui
  src/Qmitk/QmitkFitPlotDataWidget.ui
)
