set(CPP_FILES
  QmitkParameterFitBackgroundJob.cpp
  QmitkSimpleBarrierParametersDelegate.cpp
  QmitkSimpleBarrierTypeDelegate.cpp
  QmitkSimpleBarrierModel.cpp
  QmitkSimpleBarrierManagerWidget.cpp
  QmitkInitialValuesModel.cpp
  QmitkInitialValuesManagerWidget.cpp
  QmitkInitialValuesDelegate.cpp
  QmitkInitialValuesTypeDelegate.cpp
  QmitkFitParameterModel.cpp
  QmitkFitParameterWidget.cpp
  QmitkInspectionPositionWidget.cpp
  QmitkFitPlotDataWidget.cpp
  QmitkFitPlotDataModel.cpp
)

set(UI_FILES
  src/QmitkSimpleBarrierManagerWidget.ui
  src/QmitkInitialValuesManagerWidget.ui
  src/QmitkFitParameterWidget.ui
  src/QmitkInspectionPositionWidget.ui
  src/QmitkFitPlotDataWidget.ui
)
