set(CPP_FILES
  Internal/mitkIOExtActivator.cpp
  Internal/mitkIOExtObjectFactory.cpp
  Internal/mitkObjFileReaderService.cpp
  Internal/mitkPlyFileWriterService.cpp
  Internal/mitkPlyFileReaderService.cpp
  Internal/mitkParRecFileIOFactory.cpp
  Internal/mitkParRecFileReader.cpp
  Internal/mitkSceneFileReader.cpp
  Internal/mitkStlVolumeTimeSeriesIOFactory.cpp
  Internal/mitkStlVolumeTimeSeriesReader.cpp
  Internal/mitkUnstructuredGridVtkWriter.cpp
  Internal/mitkUnstructuredGridVtkWriterFactory.cpp
  Internal/mitkVtkUnstructuredGridReader.cpp
  Internal/mitkVtkVolumeTimeSeriesIOFactory.cpp
  Internal/mitkVtkVolumeTimeSeriesReader.cpp
)
