set(CPP_FILES
  mitkIOExtActivator.cpp
  mitkIOExtObjectFactory.cpp
  mitkObjFileReaderService.cpp
  mitkPlyFileWriterService.cpp
  mitkPlyFileReaderService.cpp
  mitkParRecFileIOFactory.cpp
  mitkParRecFileReader.cpp
  mitkStlVolumeTimeSeriesIOFactory.cpp
  mitkStlVolumeTimeSeriesReader.cpp
  mitkUnstructuredGridVtkWriter.cpp
  mitkUnstructuredGridVtkWriterFactory.cpp
  mitkVtkUnstructuredGridReader.cpp
  mitkVtkVolumeTimeSeriesIOFactory.cpp
  mitkVtkVolumeTimeSeriesReader.cpp
)
