set(CPP_FILES
  Internal/mitkIOExtActivator.cpp
  Internal/mitkIOExtObjectFactory.cpp
  Internal/mitkObjFileIOFactory.cpp
  Internal/mitkObjFileReader.cpp
  Internal/mitkParRecFileIOFactory.cpp
  Internal/mitkParRecFileReader.cpp
  Internal/mitkSceneFileReader.cpp
  Internal/mitkStlVolumeTimeSeriesIOFactory.cpp
  Internal/mitkStlVolumeTimeSeriesReader.cpp
  Internal/mitkUnstructuredGridVtkWriter.cpp
  Internal/mitkUnstructuredGridVtkWriterFactory.cpp
  Internal/mitkVtkUnstructuredGridIOFactory.cpp
  Internal/mitkVtkUnstructuredGridReader.cpp
  Internal/mitkVtkVolumeTimeSeriesIOFactory.cpp
  Internal/mitkVtkVolumeTimeSeriesReader.cpp
)
