set(QT_DONT_USE_QTCORE 0)
set(QT_DONT_USE_QTGUI 0)
find_package(Qt4 QUIET REQUIRED QtCore ${MODULE_QT4_MODULES}) # TODO we could need QUIET!
include(${QT_USE_FILE})
list(APPEND ALL_LIBRARIES ${QT_LIBRARIES})
