#!/usr/bin/env python3
# ============================================================================
#
# The Medical Imaging Interaction Toolkit (MITK)
#
# Copyright (c) German Cancer Research Center (DKFZ)
# All rights reserved.
#
# Use of this source code is governed by a 3-clause BSD license that can be
# found in the LICENSE file.
#
# ============================================================================

"""Generate the CPython version table used by MITK's Python3 external project.

Run once per python-build-standalone release; the output (Versions.cmake) is
committed so that configuring MITK needs no network access beyond the archive
downloads themselves:

    python generate_versions.py 20260114 Versions.cmake

The release's SHA256SUMS asset is the single source of truth: it yields both the
latest patch version per CPython series and the archive hashes, so a release
bump never involves copying hashes by hand.

Pre-release series (3.15.0a5 and the like) are ignored; only final releases have
a patch component directly followed by the '+<release>' build tag.

The set of emitted platforms mirrors the archives CMakeExternals/Python3.cmake
can actually select. Teaching MITK a new platform means adding an entry to
PLATFORMS here and regenerating.
"""

import argparse
import re
import sys
import urllib.request

BASE_URL = "https://github.com/astral-sh/python-build-standalone/releases/download"

# CMake key -> (arch, platform triple) of the archive to record. The keys are
# what CMakeExternals/Python3.cmake appends to MITK_PYTHON3_<version>_HASH_.
PLATFORMS = {
    "WIN": ("x86_64", "pc-windows-msvc"),
    "MAC_X86_64": ("x86_64", "apple-darwin"),
    "MAC_ARM64": ("aarch64", "apple-darwin"),
    "LINUX": ("x86_64_v2", "unknown-linux-gnu"),
}

VARIANT = "install_only_stripped"

ASSET_RE = re.compile(
    r"^cpython-(\d+)\.(\d+)\.(\d+)\+(\d+)-(.+)-" + VARIANT + r"\.tar\.gz$"
)


def fetch_checksums(release):
    """Return {asset name: sha256} for every archive in the release."""
    url = f"{BASE_URL}/{release}/SHA256SUMS"
    print(f"Fetching {url}")
    with urllib.request.urlopen(url) as response:
        text = response.read().decode("utf-8")

    checksums = {}
    for line in text.splitlines():
        parts = line.split()
        if len(parts) == 2:
            checksums[parts[1]] = parts[0]
    if not checksums:
        raise RuntimeError(f"no checksums parsed from {url}")
    return checksums


def latest_patches(checksums, release):
    """Return {'3.12': '3.12.12', ...} for the final releases in the release."""
    patches = {}
    for name in checksums:
        match = ASSET_RE.match(name)
        if not match or match.group(4) != release:
            continue
        series = f"{match.group(1)}.{match.group(2)}"
        patch = int(match.group(3))
        if patch > patches.get(series, -1):
            patches[series] = patch
    return {series: f"{series}.{patch}" for series, patch in patches.items()}


def archive_name(patch_version, release, arch, platform):
    return (
        f"cpython-{patch_version}+{release}-{arch}-{platform}-{VARIANT}.tar.gz"
    )


def collect(checksums, release, versions):
    """Return [(series, patch version, {key: hash})], failing on any gap."""
    available = latest_patches(checksums, release)

    missing = [v for v in versions if v not in available]
    if missing:
        raise RuntimeError(
            f"release {release} has no final CPython release for: "
            f"{', '.join(missing)} (available: {', '.join(sorted(available))})"
        )

    table = []
    for series in versions:
        patch_version = available[series]
        hashes = {}
        for key, (arch, platform) in PLATFORMS.items():
            name = archive_name(patch_version, release, arch, platform)
            if name not in checksums:
                raise RuntimeError(f"release {release} has no archive {name}")
            hashes[key] = checksums[name]
        table.append((series, patch_version, hashes))
        print(f"  {patch_version}: {len(hashes)} archives")
    return table


def write_versions_cmake(path, release, table):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("# Generated by generate_versions.py - do not edit.\n")
        f.write("# CPython releases from astral-sh/python-build-standalone:\n")
        f.write("# per series the latest patch version and the archive hashes.\n")
        f.write("#\n")
        f.write("# OpenSSL is a property of the release rather than of a single\n")
        f.write("# CPython series, so MITK_REQUIRED_OPENSSL_VERSION in the\n")
        f.write("# top-level CMakeLists.txt tracks MITK_PYTHON3_RELEASE.\n\n")
        f.write(f"set(MITK_PYTHON3_RELEASE {release})\n")
        f.write(
            'set(MITK_PYTHON3_VERSIONS "{}")\n'.format(
                ";".join(series for series, _, _ in table)
            )
        )
        for series, patch_version, hashes in table:
            key = series.replace(".", "")
            f.write(f"\nset(MITK_PYTHON3_{key}_PATCH {patch_version})\n")
            for platform_key in PLATFORMS:
                f.write(
                    f"set(MITK_PYTHON3_{key}_HASH_{platform_key} "
                    f"SHA256={hashes[platform_key]})\n"
                )


def main():
    parser = argparse.ArgumentParser(
        description="Generate Versions.cmake from a python-build-standalone release."
    )
    parser.add_argument("release", help="release tag, e.g. 20260114")
    parser.add_argument("output", help="path of the Versions.cmake to write")
    parser.add_argument(
        "--versions",
        nargs="+",
        default=["3.12", "3.13", "3.14"],
        help="CPython series to record (default: %(default)s)",
    )
    args = parser.parse_args()

    checksums = fetch_checksums(args.release)
    table = collect(checksums, args.release, args.versions)
    write_versions_cmake(args.output, args.release, table)
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
