set(Plugin-Name "FlowBench Segmentation Controll")
set(Plugin-Version "0.1")
set(Plugin-Vendor "DKFZ, Medical Image Computing")
set(Plugin-ContactAddress "http://www.mitk.org")
set(Require-Plugin org.mitk.gui.qt.common org.mitk.gui.qt.multilabelsegmentation) #org.mitk.gui.qt.flowbenchapplication)
