SET(CPP_FILES 
  mitkBaseDataIOFactory.cpp
  mitkBaseXMLWriter.cpp
  mitkChiliPluginIpPicStub.c
  mitkPACSPlugin.cpp
  mitkFileReader.cpp
  mitkFileSeriesReader.cpp
  mitkFileWriter.cpp
  mitkImageWriter.cpp
  mitkImageWriterFactory.cpp
  mitkItkImageFileIOFactory.cpp
  mitkItkImageFileReader.cpp
  mitkItkImageWrite.cpp
  mitkMeshReader.cpp
  mitkObjFileIOFactory.cpp
  mitkObjFileReader.cpp
  mitkParRecFileIOFactory.cpp
  mitkParRecFileReader.cpp
  mitkPicFileIOFactory.cpp
  mitkPicFileReader.cpp
  mitkPicFileWriter.cpp
  mitkPicVolumeTimeSeriesIOFactory.cpp
  mitkPicVolumeTimeSeriesReader.cpp
  mitkPointSetIOFactory.cpp
  mitkPointSetReader.cpp
  mitkPointSetWriter.cpp
  mitkPointSetWriterFactory.cpp
  mitkRawImageFileReader.cpp
  mitkStandardFileLocations.cpp
  mitkSTLFileIOFactory.cpp
  mitkSTLFileReader.cpp
  mitkStlVolumeTimeSeriesIOFactory.cpp
  mitkStlVolumeTimeSeriesReader.cpp
  mitkSurfaceVtkWriter.cpp
  mitkSurfaceVtkWriter.txx
  mitkSurfaceVtkWriterFactory.cpp
  mitkUnstructuredGridVtkWriter.cpp
  mitkUnstructuredGridVtkWriter.txx
  mitkUnstructuredGridVtkWriterFactory.cpp
  mitkVtiFileIOFactory.cpp
  mitkVtiFileReader.cpp
  mitkVtkImageIOFactory.cpp
  mitkVtkImageReader.cpp
  mitkVtkSurfaceIOFactory.cpp
  mitkVtkSurfaceReader.cpp
  mitkVtkUnstructuredGridIOFactory.cpp
  mitkVtkUnstructuredGridReader.cpp
  mitkVtkVolumeTimeSeriesIOFactory.cpp
  mitkVtkVolumeTimeSeriesReader.cpp
  mitkXMLReader.cpp
  mitkXMLWriter.cpp
  vtkPointSetXMLParser.cpp
  # XMLPointIO.cpp

  mitkLightBoxImageReader.cpp
)
