set(CPP_FILES
  mitkIGTLClient.cpp
  mitkIGTLServer.cpp
  mitkIGTLDevice.cpp
  mitkIGTLMessageSource.cpp
  mitkIGTLMessageCommon.cpp
  mitkIGTLDeviceSource.cpp
  mitkIGTLMessage.cpp
  mitkIGTLMessageFactory.cpp
  mitkIGTLMessageCloneHandler.h
  mitkIGTLDummyMessage.cpp
  mitkIGTLMessageQueue.cpp
  mitkIGTLMessageProvider.cpp
  mitkIGTLMeasurements.cpp
  mitkIGTLModuleActivator.cpp

  Filters/mitkImageToIGTLMessageFilter.cpp
  DeviceSources/mitkIGTL2DImageDeviceSource.cpp
  DeviceSources/mitkIGTL3DImageDeviceSource.cpp
  DeviceSources/mitkIGTLTrackingDataDeviceSource.cpp
)
