set(CPP_FILES
  mitkIGTLClient.cpp
  mitkIGTLServer.cpp
  mitkIGTLDevice.cpp
  mitkIGTLMessageSource.cpp
  mitkIGTLDeviceSource.cpp
  mitkIGTLMessage.cpp
  mitkIGTLMessageFactory.cpp
  mitkIGTLMessageCloneHandler.h
  mitkIGTLDummyMessage.cpp
  mitkIGTLMessageQueue.cpp
  mitkIGTLMessageProvider.cpp
)
