set(H_FILES
  mitkDICOMFileReader.h
  mitkDICOMImageFrameInfo.h
  mitkDICOMImageBlockDescriptor.h
  mitkDICOMGDCMImageFrameInfo.h
  mitkDICOMITKSeriesGDCMReader.h
  mitkDICOMDatasetSorter.h
  mitkDICOMFilenameSorter.h
  mitkDICOMEnums.h
  mitkDICOMTagBasedSorter.h
  mitkDICOMSortCriterion.h
  mitkDICOMSortByTag.h
  mitkEquiDistantBlocksSorter.h
)

set(CPP_FILES
  mitkDICOMFileReader.cpp
  mitkDICOMImageBlockDescriptor.cpp
  mitkDICOMITKSeriesGDCMReader.cpp
  mitkDICOMDatasetSorter.cpp
  mitkDICOMFilenameSorter.cpp
  mitkDICOMTagBasedSorter.cpp
  mitkDICOMGDCMImageFrameInfo.cpp
  mitkDICOMImageFrameInfo.cpp
  mitkDICOMSortCriterion.cpp
  mitkDICOMSortByTag.cpp
  mitkITKDICOMSeriesReaderHelper.cpp
  mitkEquiDistantBlocksSorter.cpp
  mitkGantryTiltInformation.cpp
)
