set(CPP_FILES
  mitkOclUtils.cpp
  mitkOclResourceServiceImpl_Private.cpp
  mitkOclImageFormats.cpp
  mitkOpenCLActivator.cpp
  mitkOclBaseData.cpp
  mitkOclImage.cpp
  mitkOclFilter.cpp
  mitkOclImageFilter.cpp
  mitkOclImageToImageFilter.cpp
)
