#undef find
#undef _ipCp
#undef _ipEndian
#undef ipErrorStr
#undef ipFReadCvt
#undef ipFWriteCvt
#undef write_compressed
#undef _ipCpCvtEndian
#undef _ipCvtEndian
#undef ipFuncAbove
#undef ipFuncAddC
#undef ipFuncAddI
#undef ipFuncAddSl
#undef ipFuncAnd
#undef ipFuncBeneath
#undef ipFuncBorder
#undef _ipFuncBorder
#undef ipFuncBorderOld
#undef ipFuncBorderX
#undef _ipFuncBorderX
#undef ipFuncBorderZero
#undef ipFuncBox
#undef _ipFuncBox2d
#undef _ipFuncBox3d
#undef ipFuncBox_t
#undef ipFuncCanny
#undef ipFuncClose
#undef ipFuncCloseF
#undef ipFuncCompressM
#undef _ipFuncCompressM
#undef ipFuncConv
#undef ipFuncConvert
#undef ipFuncCopyTags
#undef ipFuncCurtosis
#undef ipFuncCurtosisR
#undef ipFunc_DEPENDENCIES
#undef ipFuncDila
#undef ipFuncDilaF
#undef ipFuncDivC
#undef ipFuncDivI
#undef ipFuncDrawPoly
#undef _ipFuncDrawPoly
#undef ipFuncEqual
#undef ipFuncEro
#undef ipFuncEroF
#undef ipFuncErrno
#undef _ipFuncError
#undef ipFuncExp
#undef ipFuncExtr
#undef _ipFuncExtr
#undef ipFuncExtrC
#undef ipFuncExtrR
#undef ipFuncExtrROI
#undef _ipFuncExtT
#undef ipFuncFillArea
#undef ipFuncFlagBorderOld
#undef ipFuncFlagBorderZero
#undef ipFuncFlagF_MAX
#undef _ipFuncFlagF_t
#undef ipFuncFlagI_MAX
#undef ipFuncFlagI_t
#undef ipFuncFrame
#undef ipFuncGausF
#undef ipFuncGaussF
#undef ipFuncGrad
#undef ipFuncGrav
#undef ipFuncHist
#undef _ipFuncHist
#undef ipFuncHisto
#undef ipFuncHitMiss
#undef ipFuncHitMissI
#undef _ipFuncHitMissI
#undef ipFuncInertia
#undef ipFuncInv
#undef ipFuncKeep
#undef ipFuncLabel
#undef ipFuncLaplace
#undef ipFunc_LDADD
#undef ipFunc_LDFLAGS
#undef ipFunclevWin
#undef ipFuncLevWin
#undef ipFuncLib
#undef ipFuncLN
#undef ipFuncLog
#undef ipFuncMain
#undef ipFuncMakePicName
#undef ipFuncMalloc
#undef _ipFuncMalloc
#undef ipFuncMasc_t
#undef ipFuncMean
#undef ipFuncMeanC
#undef ipFuncMeanF
#undef ipFuncMeanR
#undef ipFuncMeanROI
#undef ipFuncMedI
#undef ipFuncMinMax
#undef ipFuncMorph
#undef _ipFuncMorph
#undef ipFuncMultC
#undef ipFuncMultI
#undef ipFuncNoKeep
#undef ipFuncNoReflect
#undef ipFuncNorm
#undef ipFuncNormXY
#undef ipFuncNot
#undef ipFunc_OBJECTS
#undef ipFuncOpCl
#undef _ipFuncOpCl
#undef ipFuncOpen
#undef ipFuncOpenF
#undef ipFuncOr
#undef ipFuncP
#undef ipFuncPError
#undef ipFuncPot
#undef ipFuncRange
#undef ipFuncRank
#undef ipFuncRefl
#undef ipFuncReflect
#undef ipFuncRegGrow
#undef ipFuncResultFunction
#undef ipFuncResultOffset
#undef ipFuncRoberts
#undef ipFuncRotate
#undef ipFuncScale
#undef ipFuncScaleBl
#undef _ipFuncScaleBL
#undef ipFuncScaleNN
#undef _ipFuncScBL
#undef ipFuncScFact
#undef _ipFuncScNN
#undef ipFuncSDev
#undef ipFuncSDevC
#undef ipFuncSDevR
#undef ipFuncSDevROI
#undef ipFuncSelect
#undef ipFuncSelInv
#undef ipFuncSelMM
#undef ipFuncSelMM_Inv
#undef _ipFuncSetErrno
#undef ipFuncSetTag
#undef ipFuncShapeInterpolation
#undef ipFuncShp
#undef ipFuncSkewness
#undef ipFuncSkewnessR
#undef ipFuncSobel
#undef ipFuncSourceIndex
#undef ipFuncSourceOffset
#undef ipFunc_SOURCES
#undef ipFuncSqrt
#undef ipFuncSubC
#undef ipFuncSubI
#undef ipFuncThresh
#undef ipFuncTotal
#undef ipFuncTranspose
#undef ipFuncVar
#undef ipFuncVarC
#undef ipFuncVarR
#undef ipFuncVarROI
#undef ipFunc___Win32_Debug
#undef ipFunc___Win32_Release
#undef ipFuncWindow
#undef ipFuncWindowR
#undef ipFuncXchange
#undef ipFuncZeroCr
#undef ipPicAccess
#undef ipPicAddSubTag
#undef ipPicAddT
#undef ipPicAddTag
#undef ipPicAnnotation
#undef ipPicAnnotations
#undef ipPicAnnotations_t
#undef ipPicAnnotation_t
#undef ipPicAnnotationType_t
#undef ipPicASCII
#undef ipPicAText
#undef ipPicAUnknown
#undef ipPicBool
#undef _ipPicCanReadCompressed
#undef _ipPicCanWriteCompressed
#undef ipPicClear
#undef ipPicClone
#undef _ipPicCloneTag
#undef _ipPicCloneTags
#undef ipPicComplex
#undef ipPicCopyH
#undef ipPicCopyHeader
#undef ipPicCopyS
#undef ipPicCopySlice
#undef _ipPicCopySlice
#undef ipPicDelSubTag
#undef ipPicDelT
#undef ipPicDelTag
#undef ipPicDescriptor
#undef ipPicDescriptor_m
#undef ipPicElements
#undef _ipPicElements
#undef _ipPicFindTag
#undef ipPicFloat
#undef ipPicFORALL_x
#undef ipPicFReadCvt
#undef ipPicFree
#undef ipPicFreeTag
#undef _ipPicFreeTags
#undef _ipPicFWrite
#undef ipPicFWriteCvt
#undef ipPicGet
#undef ipPicGetH
#undef ipPicGetHeader
#undef ipPicGetMem
#undef ipPicGetS
#undef ipPicGetSlice
#undef ipPicGetT
#undef ipPicGetTag
#undef ipPicGetTags
#undef ipPicGetWriteCompression
#undef ipPicInfo
#undef _ipPicInfo
#undef _ipPicInfoPrintTags
#undef _ipPicInfo_t
#undef _ipPicInsertTag
#undef ipPicInt
#undef _ipPicMagic_t
#undef ipPicNew
#undef ipPicNewTag
#undef ipPicNonUniform
#undef ipPicOldGet
#undef _ipPicOldGet
#undef ipPicOldGetH
#undef _ipPicOldGetHeader
#undef ipPicOldGetS
#undef _ipPicOldGetSlice
#undef _ipPicOldHeader
#undef ipPicOldP
#undef ipPicOP
#undef _ipPicOpenPicFileIn
#undef ipPicPicDescriptor_m
#undef ipPicPut
#undef ipPicPutHeader
#undef ipPicPutMem
#undef ipPicPutS
#undef ipPicPutSlice
#undef ipPicQuerySubT
#undef ipPicQuerySubTag
#undef ipPicQueryT
#undef ipPicQueryTag
#undef _ipPicReadTags
#undef _ipPicReadTagsMem
#undef ipPicRemoveFile
#undef _ipPicRemoveTag
#undef ipPicSetWriteCompression
#undef ipPicSize
#undef _ipPicSize
#undef ipPicTagName
#undef _ipPicTagsElement_s
#undef _ipPicTagsElement_t
#undef _ipPicTagsNumber
#undef _ipPicTagsSize
#undef ipPicTag_t
#undef ipPicTSV
#undef ipPicTSVElements
#undef _ipPicTSVElements
#undef ipPicTSVSize
#undef _ipPicTSVSize
#undef ipPicTSV_t
#undef ipPicType
#undef _ipPicTypeMax
#undef ipPicTypeMultiplex
#undef ipPicTypeName
#undef _ipPicTypeName
#undef ipPicType_t
#undef ipPicUInt
#undef ipPicUnknown
#undef ipPicUnknown_m
#undef ipPicVersionEncryption
#undef _ipPicWriteTags
#undef _ipPicWriteTagsMem
