/*
 * This list is generated from ipPic and ipFunc
 *
 * to generate it, use something like this:
 * find mitk/Utilities/ip*c -name .svn -prune -o -exec egrep -o '\b_?ip(Pic|Func|Cvt|Cp)[a-zA-Z0-9_]+' {} \; | sort | uniq | sed 's/^\(_\?\)ip\(.*\)/#define \1ip\2 \1mitkIp\2/'
 *
 * after that add: 
 * _ipCp
 * _ipEndian
 * ipErrorStr
 * ipFReadCvt
 * ipFWriteCvt
 */
 
#ifndef MITK_IP_PIC_MANGLE_H_DEFINED
#define MITK_IP_PIC_MANGLE_H_DEFINED

#define _ipCp _mitkIpCp
#define _ipEndian _mitkIpEndian
#define ipErrorStr mitkIpErrorStr
#define ipFReadCvt mitkIpFReadCvt
#define ipFWriteCvt mitkIpFWriteCvt
#define _ipFWrite _mitkIpFWrite
#define write_compressed mitk_write_compressed


#define _ipCpCvtEndian _mitkIpCpCvtEndian
#define _ipCvtEndian _mitkIpCvtEndian
#define ipFuncAbove mitkIpFuncAbove
#define ipFuncAddC mitkIpFuncAddC
#define ipFuncAddI mitkIpFuncAddI
#define ipFuncAddSl mitkIpFuncAddSl
#define ipFuncAnd mitkIpFuncAnd
#define ipFuncBeneath mitkIpFuncBeneath
#define ipFuncBorder mitkIpFuncBorder
#define _ipFuncBorder _mitkIpFuncBorder
#define ipFuncBorderOld mitkIpFuncBorderOld
#define ipFuncBorderX mitkIpFuncBorderX
#define _ipFuncBorderX _mitkIpFuncBorderX
#define ipFuncBorderZero mitkIpFuncBorderZero
#define ipFuncBox mitkIpFuncBox
#define _ipFuncBox2d _mitkIpFuncBox2d
#define _ipFuncBox3d _mitkIpFuncBox3d
#define ipFuncBox_t mitkIpFuncBox_t
#define ipFuncCanny mitkIpFuncCanny
#define ipFuncClose mitkIpFuncClose
#define ipFuncCloseF mitkIpFuncCloseF
#define ipFuncCompressM mitkIpFuncCompressM
#define _ipFuncCompressM _mitkIpFuncCompressM
#define ipFuncConv mitkIpFuncConv
#define ipFuncConvert mitkIpFuncConvert
#define ipFuncCopyTags mitkIpFuncCopyTags
#define ipFuncCurtosis mitkIpFuncCurtosis
#define ipFuncCurtosisR mitkIpFuncCurtosisR
#define ipFunc_DEPENDENCIES mitkIpFunc_DEPENDENCIES
#define ipFuncDila mitkIpFuncDila
#define ipFuncDilaF mitkIpFuncDilaF
#define ipFuncDivC mitkIpFuncDivC
#define ipFuncDivI mitkIpFuncDivI
#define ipFuncDrawPoly mitkIpFuncDrawPoly
#define _ipFuncDrawPoly _mitkIpFuncDrawPoly
#define ipFuncEqual mitkIpFuncEqual
#define ipFuncEro mitkIpFuncEro
#define ipFuncEroF mitkIpFuncEroF
#define ipFuncErrno mitkIpFuncErrno
#define _ipFuncError _mitkIpFuncError
#define ipFuncExp mitkIpFuncExp
#define ipFuncExtr mitkIpFuncExtr
#define _ipFuncExtr _mitkIpFuncExtr
#define ipFuncExtrC mitkIpFuncExtrC
#define ipFuncExtrR mitkIpFuncExtrR
#define ipFuncExtrROI mitkIpFuncExtrROI
#define _ipFuncExtT _mitkIpFuncExtT
#define ipFuncFillArea mitkIpFuncFillArea
#define ipFuncFlagBorderOld mitkIpFuncFlagBorderOld
#define ipFuncFlagBorderZero mitkIpFuncFlagBorderZero
#define ipFuncFlagF_MAX mitkIpFuncFlagF_MAX
#define _ipFuncFlagF_t _mitkIpFuncFlagF_t
#define ipFuncFlagI_MAX mitkIpFuncFlagI_MAX
#define ipFuncFlagI_t mitkIpFuncFlagI_t
#define ipFuncFrame mitkIpFuncFrame
#define ipFuncGausF mitkIpFuncGausF
#define ipFuncGaussF mitkIpFuncGaussF
#define ipFuncGrad mitkIpFuncGrad
#define ipFuncGrav mitkIpFuncGrav
#define ipFuncHist mitkIpFuncHist
#define _ipFuncHist _mitkIpFuncHist
#define ipFuncHisto mitkIpFuncHisto
#define ipFuncHitMiss mitkIpFuncHitMiss
#define ipFuncHitMissI mitkIpFuncHitMissI
#define _ipFuncHitMissI _mitkIpFuncHitMissI
#define ipFuncInertia mitkIpFuncInertia
#define ipFuncInv mitkIpFuncInv
#define ipFuncKeep mitkIpFuncKeep
#define ipFuncLabel mitkIpFuncLabel
#define ipFuncLaplace mitkIpFuncLaplace
#define ipFunc_LDADD mitkIpFunc_LDADD
#define ipFunc_LDFLAGS mitkIpFunc_LDFLAGS
#define ipFunclevWin mitkIpFunclevWin
#define ipFuncLevWin mitkIpFuncLevWin
#define ipFuncLib mitkIpFuncLib
#define ipFuncLN mitkIpFuncLN
#define ipFuncLog mitkIpFuncLog
#define ipFuncMain mitkIpFuncMain
#define ipFuncMakePicName mitkIpFuncMakePicName
#define ipFuncMalloc mitkIpFuncMalloc
#define _ipFuncMalloc _mitkIpFuncMalloc
#define ipFuncMasc_t mitkIpFuncMasc_t
#define ipFuncMean mitkIpFuncMean
#define ipFuncMeanC mitkIpFuncMeanC
#define ipFuncMeanF mitkIpFuncMeanF
#define ipFuncMeanR mitkIpFuncMeanR
#define ipFuncMeanROI mitkIpFuncMeanROI
#define ipFuncMedI mitkIpFuncMedI
#define ipFuncMinMax mitkIpFuncMinMax
#define ipFuncMorph mitkIpFuncMorph
#define _ipFuncMorph _mitkIpFuncMorph
#define ipFuncMultC mitkIpFuncMultC
#define ipFuncMultI mitkIpFuncMultI
#define ipFuncNoKeep mitkIpFuncNoKeep
#define ipFuncNoReflect mitkIpFuncNoReflect
#define ipFuncNorm mitkIpFuncNorm
#define ipFuncNormXY mitkIpFuncNormXY
#define ipFuncNot mitkIpFuncNot
#define ipFunc_OBJECTS mitkIpFunc_OBJECTS
#define ipFuncOpCl mitkIpFuncOpCl
#define _ipFuncOpCl _mitkIpFuncOpCl
#define ipFuncOpen mitkIpFuncOpen
#define ipFuncOpenF mitkIpFuncOpenF
#define ipFuncOr mitkIpFuncOr
#define ipFuncP mitkIpFuncP
#define ipFuncPError mitkIpFuncPError
#define ipFuncPot mitkIpFuncPot
#define ipFuncRange mitkIpFuncRange
#define ipFuncRank mitkIpFuncRank
#define ipFuncRefl mitkIpFuncRefl
#define ipFuncReflect mitkIpFuncReflect
#define ipFuncRegGrow mitkIpFuncRegGrow
#define ipFuncResultFunction mitkIpFuncResultFunction
#define ipFuncResultOffset mitkIpFuncResultOffset
#define ipFuncRoberts mitkIpFuncRoberts
#define ipFuncRotate mitkIpFuncRotate
#define ipFuncScale mitkIpFuncScale
#define ipFuncScaleBl mitkIpFuncScaleBl
#define _ipFuncScaleBL _mitkIpFuncScaleBL
#define ipFuncScaleNN mitkIpFuncScaleNN
#define _ipFuncScBL _mitkIpFuncScBL
#define ipFuncScFact mitkIpFuncScFact
#define _ipFuncScNN _mitkIpFuncScNN
#define ipFuncSDev mitkIpFuncSDev
#define ipFuncSDevC mitkIpFuncSDevC
#define ipFuncSDevR mitkIpFuncSDevR
#define ipFuncSDevROI mitkIpFuncSDevROI
#define ipFuncSelect mitkIpFuncSelect
#define ipFuncSelInv mitkIpFuncSelInv
#define ipFuncSelMM mitkIpFuncSelMM
#define ipFuncSelMM_Inv mitkIpFuncSelMM_Inv
#define _ipFuncSetErrno _mitkIpFuncSetErrno
#define ipFuncSetTag mitkIpFuncSetTag
#define ipFuncShapeInterpolation mitkIpFuncShapeInterpolation
#define ipFuncShp mitkIpFuncShp
#define ipFuncSkewness mitkIpFuncSkewness
#define ipFuncSkewnessR mitkIpFuncSkewnessR
#define ipFuncSobel mitkIpFuncSobel
#define ipFuncSourceIndex mitkIpFuncSourceIndex
#define ipFuncSourceOffset mitkIpFuncSourceOffset
#define ipFunc_SOURCES mitkIpFunc_SOURCES
#define ipFuncSqrt mitkIpFuncSqrt
#define ipFuncSubC mitkIpFuncSubC
#define ipFuncSubI mitkIpFuncSubI
#define ipFuncThresh mitkIpFuncThresh
#define ipFuncTotal mitkIpFuncTotal
#define ipFuncTranspose mitkIpFuncTranspose
#define ipFuncVar mitkIpFuncVar
#define ipFuncVarC mitkIpFuncVarC
#define ipFuncVarR mitkIpFuncVarR
#define ipFuncVarROI mitkIpFuncVarROI
#define ipFunc___Win32_Debug mitkIpFunc___Win32_Debug
#define ipFunc___Win32_Release mitkIpFunc___Win32_Release
#define ipFuncWindow mitkIpFuncWindow
#define ipFuncWindowR mitkIpFuncWindowR
#define ipFuncXchange mitkIpFuncXchange
#define ipFuncZeroCr mitkIpFuncZeroCr
#define ipPicAccess mitkIpPicAccess
#define ipPicAddSubTag mitkIpPicAddSubTag
#define ipPicAddT mitkIpPicAddT
#define ipPicAddTag mitkIpPicAddTag
#define ipPicAnnotation mitkIpPicAnnotation
#define ipPicAnnotations mitkIpPicAnnotations
#define ipPicAnnotations_t mitkIpPicAnnotations_t
#define ipPicAnnotation_t mitkIpPicAnnotation_t
#define ipPicAnnotationType_t mitkIpPicAnnotationType_t
#define ipPicASCII mitkIpPicASCII
#define ipPicAText mitkIpPicAText
#define ipPicAUnknown mitkIpPicAUnknown
#define ipPicBool mitkIpPicBool
#define _ipPicCanReadCompressed _mitkIpPicCanReadCompressed
#define _ipPicCanWriteCompressed _mitkIpPicCanWriteCompressed
#define ipPicClear mitkIpPicClear
#define ipPicClone mitkIpPicClone
#define _ipPicCloneTag _mitkIpPicCloneTag
#define _ipPicCloneTags _mitkIpPicCloneTags
#define ipPicComplex mitkIpPicComplex
#define ipPicCopyH mitkIpPicCopyH
#define ipPicCopyHeader mitkIpPicCopyHeader
#define ipPicCopyS mitkIpPicCopyS
#define ipPicCopySlice mitkIpPicCopySlice
#define _ipPicCopySlice _mitkIpPicCopySlice
#define ipPicDelSubTag mitkIpPicDelSubTag
#define ipPicDelT mitkIpPicDelT
#define ipPicDelTag mitkIpPicDelTag
#define ipPicDescriptor mitkIpPicDescriptor
#define ipPicDescriptor_m mitkIpPicDescriptor_m
#define ipPicElements mitkIpPicElements
#define _ipPicElements _mitkIpPicElements
#define _ipPicFindTag _mitkIpPicFindTag
#define ipPicFloat mitkIpPicFloat
#define ipPicFORALL_x mitkIpPicFORALL_x
#define ipPicFReadCvt mitkIpPicFReadCvt
#define ipPicFree mitkIpPicFree
#define ipPicFreeTag mitkIpPicFreeTag
#define _ipPicFreeTags _mitkIpPicFreeTags
#define _ipPicFWrite _mitkIpPicFWrite
#define ipPicFWriteCvt mitkIpPicFWriteCvt
#define ipPicGet mitkIpPicGet
#define ipPicGetH mitkIpPicGetH
#define ipPicGetHeader mitkIpPicGetHeader
#define ipPicGetMem mitkIpPicGetMem
#define ipPicGetS mitkIpPicGetS
#define ipPicGetSlice mitkIpPicGetSlice
#define ipPicGetT mitkIpPicGetT
#define ipPicGetTag mitkIpPicGetTag
#define ipPicGetTags mitkIpPicGetTags
#define ipPicGetWriteCompression mitkIpPicGetWriteCompression
#define ipPicInfo mitkIpPicInfo
#define _ipPicInfo _mitkIpPicInfo
#define _ipPicInfoPrintTags _mitkIpPicInfoPrintTags
#define _ipPicInfo_t _mitkIpPicInfo_t
#define _ipPicInsertTag _mitkIpPicInsertTag
#define ipPicInt mitkIpPicInt
#define _ipPicMagic_t _mitkIpPicMagic_t
#define ipPicNew mitkIpPicNew
#define ipPicNewTag mitkIpPicNewTag
#define ipPicNonUniform mitkIpPicNonUniform
#define ipPicOldGet mitkIpPicOldGet
#define _ipPicOldGet _mitkIpPicOldGet
#define ipPicOldGetH mitkIpPicOldGetH
#define _ipPicOldGetHeader _mitkIpPicOldGetHeader
#define ipPicOldGetS mitkIpPicOldGetS
#define _ipPicOldGetSlice _mitkIpPicOldGetSlice
#define _ipPicOldHeader _mitkIpPicOldHeader
#define ipPicOldP mitkIpPicOldP
#define ipPicOP mitkIpPicOP
#define _ipPicOpenPicFileIn _mitkIpPicOpenPicFileIn
#define ipPicPicDescriptor_m mitkIpPicPicDescriptor_m
#define ipPicPut mitkIpPicPut
#define ipPicPutHeader mitkIpPicPutHeader
#define ipPicPutMem mitkIpPicPutMem
#define ipPicPutS mitkIpPicPutS
#define ipPicPutSlice mitkIpPicPutSlice
#define ipPicQuerySubT mitkIpPicQuerySubT
#define ipPicQuerySubTag mitkIpPicQuerySubTag
#define ipPicQueryT mitkIpPicQueryT
#define ipPicQueryTag mitkIpPicQueryTag
#define _ipPicReadTags _mitkIpPicReadTags
#define _ipPicReadTagsMem _mitkIpPicReadTagsMem
#define ipPicRemoveFile mitkIpPicRemoveFile
#define _ipPicRemoveTag _mitkIpPicRemoveTag
#define ipPicSetWriteCompression mitkIpPicSetWriteCompression
#define ipPicSize mitkIpPicSize
#define _ipPicSize _mitkIpPicSize
#define ipPicTagName mitkIpPicTagName
#define _ipPicTagsElement_s _mitkIpPicTagsElement_s
#define _ipPicTagsElement_t _mitkIpPicTagsElement_t
#define _ipPicTagsNumber _mitkIpPicTagsNumber
#define _ipPicTagsSize _mitkIpPicTagsSize
#define ipPicTag_t mitkIpPicTag_t
#define ipPicTSV mitkIpPicTSV
#define ipPicTSVElements mitkIpPicTSVElements
#define _ipPicTSVElements _mitkIpPicTSVElements
#define ipPicTSVSize mitkIpPicTSVSize
#define _ipPicTSVSize _mitkIpPicTSVSize
#define ipPicTSV_t mitkIpPicTSV_t
#define ipPicType mitkIpPicType
#define _ipPicTypeMax _mitkIpPicTypeMax
#define ipPicTypeMultiplex mitkIpPicTypeMultiplex
#define ipPicTypeName mitkIpPicTypeName
#define _ipPicTypeName _mitkIpPicTypeName
#define ipPicType_t mitkIpPicType_t
#define ipPicUInt mitkIpPicUInt
#define ipPicUnknown mitkIpPicUnknown
#define ipPicUnknown_m mitkIpPicUnknown_m
#define ipPicVersionEncryption mitkIpPicVersionEncryption
#define _ipPicWriteTags _mitkIpPicWriteTags
#define _ipPicWriteTagsMem _mitkIpPicWriteTagsMem

#endif
