SET(CPP_FILES
  mitkPinholeCameraModel.cpp
  mitkToFCompositeFilter.cpp
  mitkToFDistanceImageToPointSetFilter.cpp
  mitkToFDistanceImageToSurfaceFilter.cpp
  mitkToFProcessingCommon.cpp  
  mitkToFSurfaceVtkMapper3D.cpp
  mitkToFVisualizationFilter.cpp
  mitkToFTestingCommon.cpp
)
