SET(CPP_FILES
  mitkToFCompositeFilter.cpp
  mitkToFDistanceImageToPointSetFilter.cpp
  mitkToFDistanceImageToSurfaceFilter.cpp
  mitkToFImageDownsamplingFilter.cpp
  mitkToFProcessingCommon.cpp  
  mitkToFSurfaceVtkMapper3D.cpp
  mitkToFTestingCommon.cpp
)
