language: cpp
compiler:
  - gcc
  - clang
env:
  - BUILD_CONFIGURATION=0
  - BUILD_CONFIGURATION=1
  - BUILD_CONFIGURATION=2
  - BUILD_CONFIGURATION=3
  - BUILD_CONFIGURATION=4
  - BUILD_CONFIGURATION=5
  - BUILD_CONFIGURATION=6
  - BUILD_CONFIGURATION=7
  - BUILD_CONFIGURATION=8
  - BUILD_CONFIGURATION=9
  - BUILD_CONFIGURATION=10
  - BUILD_CONFIGURATION=11
  - BUILD_CONFIGURATION=12
  - BUILD_CONFIGURATION=13
  - BUILD_CONFIGURATION=14
  - BUILD_CONFIGURATION=15

branches:
  only:
    - master

script: ctest -S ./CMake/usCTestScript_travis.cmake
