/*============================================================================

The Medical Imaging Interaction Toolkit (MITK)

Copyright (c) German Cancer Research Center (DKFZ)
All rights reserved.

Use of this source code is governed by a 3-clause BSD license that can be
found in the LICENSE file.

============================================================================*/

#include "berryICommandService.h"

#include "berryCommandManager.h"

namespace berry {

const QString ICommandService::AUTOGENERATED_CATEGORY_ID()
{
  static QString str(CommandManager::AUTOGENERATED_CATEGORY_ID);
  return str;
}

}
