SET(MODULE_TESTS
  itkMultiOutputNaryFunctorImageFilterTest.cpp
  itkMaskedStatisticsImageFilterTest.cpp
  itkMaskedNaryStatisticsImageFilterTest.cpp
  mitkLevenbergMarquardtModelFitFunctorTest.cpp
  mitkPixelBasedParameterFitImageGeneratorTest.cpp
  mitkROIBasedParameterFitImageGeneratorTest.cpp
  mitkMaskedDynamicImageStatisticsGeneratorTest.cpp
  mitkModelFitInfoTest.cpp
  mitkModelFitStaticParameterMapTest.cpp
  mitkSimpleBarrierConstraintCheckerTest.cpp
  mitkMVConstrainedCostFunctionDecoratorTest.cpp
  mitkConcreteModelFactoryBaseTest.cpp
  mitkFormulaParserTest.cpp
  mitkModelFitResultRelationRuleTest.cpp
  mitkT2DecayModelTest.cpp
  mitkLinearModelTest.cpp
  mitkExpDecayOffsetModelTest.cpp
)
