set(CPP_FILES
  Algorithms/mitkContourModelSource.cpp
  Algorithms/mitkContourModelSetSource.cpp
  Algorithms/mitkContourModelSubDivisionFilter.cpp
  Algorithms/mitkContourModelToPointSetFilter.cpp
  Algorithms/mitkContourModelToSurfaceFilter.cpp
  Algorithms/mitkImageToContourModelFilter.cpp
  Algorithms/mitkContourObjectFactory.cpp
  Algorithms/mitkContourModelUtils.cpp
  DataManagement/mitkContourModel.cpp
  DataManagement/mitkContourModelSet.cpp
  DataManagement/mitkContourElement.cpp
  Rendering/mitkContourModelGLMapper2D.cpp
  Rendering/mitkContourModelMapper2D.cpp
  Rendering/mitkContourModelMapper3D.cpp
  Rendering/mitkContourModelSetMapper3D.cpp
  Rendering/mitkContourModelSetGLMapper2D.cpp
  Rendering/mitkContourModelGLMapper2DBase.cpp
  IO/mitkContourModelSerializer.cpp
  IO/mitkContourModelReader.cpp
  IO/mitkContourModelWriter.cpp
  IO/mitkContourModelSetSerializer.cpp
  IO/mitkContourModelSetReader.cpp
  IO/mitkContourModelSetWriter.cpp
  mitkContourModelActivator.cpp
)
