set(CPP_FILES
  mitkCheckboxesQuestion.cpp
  mitkDropdownQuestion.cpp
  mitkForm.cpp
  mitkIQuestionFactory.cpp
  mitkLinearScaleQuestion.cpp
  mitkModuleActivator.cpp
  mitkMultipleChoiceQuestion.cpp
  mitkParagraphQuestion.cpp
  mitkQuestion.cpp
  mitkQuestionFactory.cpp
  mitkQuestionWithOptions.cpp
  mitkQuestionWithOtherOption.cpp
  mitkScreenshotQuestion.cpp
  mitkShortAnswerQuestion.cpp
  mitkTextQuestion.cpp
)
