set(CPP_FILES
    mitkDiffusionMiniApps.cpp
    MiniAppManager.cpp
    FileFormatConverter.cpp
    TensorReconstruction.cpp
    QballReconstruction.cpp
    DiffusionIndices.cpp
    CopyGeometry.cpp
    GibbsTracking.cpp
    StreamlineTracking.cpp
    FiberProcessing.cpp
    LocalDirectionalFiberPlausibility.cpp
    #TractogramAngularError.cpp
    FiberDirectionExtraction.cpp
    PeakExtraction.cpp
    PeaksAngularError.cpp
    MultishellMethods.cpp
    #FiberFoxProcessing.cpp
    ExportShImage.cpp
    NetworkCreation.cpp
    NetworkStatistics.cpp
    DICOMLoader.cpp
)
