SET(QMITK_CPP ${QMITK_CPP}
QmitkPropertyObservers/PropertyViewTestWidget.cpp
QmitkPropertyObservers/QmitkBasePropertyView.cpp
QmitkPropertyObservers/QmitkBoolPropertyEditor.cpp
QmitkPropertyObservers/QmitkBoolPropertyView.cpp
QmitkPropertyObservers/QmitkColorPropertyEditor.cpp
QmitkPropertyObservers/QmitkColorPropertyView.cpp
QmitkPropertyObservers/QmitkDataTreeComboBox.cpp
QmitkPropertyObservers/QmitkDataTreeListView.cpp
QmitkPropertyObservers/QmitkDataTreeListViewExpander.cpp
QmitkPropertyObservers/QmitkNumberPropertyEditor.cpp
QmitkPropertyObservers/QmitkNumberPropertyView.cpp
QmitkPropertyObservers/QmitkPropertyViewFactory.cpp
QmitkPropertyObservers/QmitkStringPropertyEditor.cpp
QmitkPropertyObservers/QmitkStringPropertyOnDemandEdit.cpp
QmitkPropertyObservers/QmitkStringPropertyView.cpp
# QmitkPropertyObservers/testmain.cpp
)
SET(QMITK_MOC_H ${QMITK_MOC_H}
QmitkPropertyObservers/PropertyViewTestWidget.h
QmitkPropertyObservers/QmitkBasePropertyView.h
QmitkPropertyObservers/QmitkBoolPropertyEditor.h
QmitkPropertyObservers/QmitkBoolPropertyView.h
QmitkPropertyObservers/QmitkColorPropertyEditor.h
QmitkPropertyObservers/QmitkColorPropertyView.h
QmitkPropertyObservers/QmitkDataTreeComboBox.h
QmitkPropertyObservers/QmitkDataTreeListViewExpander.h
QmitkPropertyObservers/QmitkDataTreeListView.h
QmitkPropertyObservers/QmitkNumberPropertyEditor.h
QmitkPropertyObservers/QmitkNumberPropertyView.h
QmitkPropertyObservers/QmitkStringPropertyEditor.h
QmitkPropertyObservers/QmitkStringPropertyOnDemandEdit.h
QmitkPropertyObservers/QmitkStringPropertyView.h
)
