set(enabled_modules
  AlgorithmsExt
  Annotation
  AppUtil
  BoundingShape
  CommandLine
  ContourModel
  Core
  CppMicroServices
  DataTypesExt
  DICOM
  DICOMImageIO
  DICOMPM
  DICOMPMIO
  DICOMQI
  DICOMSegIO
  Forms
  FormsUI
  GraphAlgorithms
  ImageExtraction
  ImageStatistics
  IOExt
  LegacyGL
  LegacyIO
  Log
  MapperExt
  ModelFit
  Multilabel
  MultilabelIO
  PlanarFigure
  QtWidgets
  QtWidgetsExt
  SceneSerialization
  SceneSerializationBase
  Segmentation
  SegmentationIO
  SegmentationUI
  SurfaceInterpolation
)

set(enabled_plugins
  org.blueberry.core.commands
  org.blueberry.core.expressions
  org.blueberry.core.runtime
  org.blueberry.ui.qt
  org.blueberry.ui.qt.help
  org.blueberry.ui.qt.log
  org.mitk.core.services
  org.mitk.gui.common
  org.mitk.gui.qt.application
  org.mitk.gui.qt.common
  org.mitk.gui.qt.datamanager
  org.mitk.gui.qt.ext
  org.mitk.gui.qt.flow.segmentation
  org.mitk.gui.qt.flowapplication
  org.mitk.gui.qt.imagenavigator
  org.mitk.gui.qt.properties
  org.mitk.gui.qt.segmentation
  org.mitk.gui.qt.stdmultiwidgeteditor
)
