set(enabled_modules
  Core
  CppMicroServices
  DICOM
  DICOMPM
  DataTypesExt
  AlgorithmsExt
  DICOMQI
  Multilabel
  SceneSerializationBase
  DICOMPMIO
  DICOMImageIO
  ContourModel
  DICOMSegIO
  LegacyGL
  MapperExt
  SceneSerialization
  LegacyIO
  IOExt
  MultilabelIO
  AppUtil
  QtWidgets
  QtWidgetsExt
  Segmentation
  SegmentationUI
  PlanarFigure
  Annotation
  IpSegmentation
  IpFunc
  SurfaceInterpolation
  GraphAlgorithms
  ImageExtraction
  ImageStatistics
)

set(enabled_plugins
org.blueberry.core.commands
org.blueberry.core.expressions
org.blueberry.core.runtime
org.blueberry.ui.qt
org.blueberry.ui.qt.help
org.blueberry.ui.qt.log
org.mitk.core.ext
org.mitk.core.services
org.mitk.gui.common
org.mitk.gui.qt.application
org.mitk.gui.qt.common
org.mitk.gui.qt.datamanager
org.mitk.gui.qt.flow.segmentation
org.mitk.gui.qt.flowapplication
org.mitk.gui.qt.imagenavigator
org.mitk.gui.qt.multilabelsegmentation
org.mitk.gui.qt.properties
org.mitk.gui.qt.segmentation
org.mitk.gui.qt.stdmultiwidgeteditor
org.mitk.planarfigure
)
