set(MODULE_TESTS
  mitkComputeContourSetNormalsFilterTest.cpp
  mitkCreateDistanceImageFromSurfaceFilterTest.cpp
  mitkImageToPointCloudFilterTest.cpp
  mitkPointCloudScoringFilterTest
  mitkReduceContourSetFilterTest.cpp
  mitkSurfaceInterpolationControllerTest.cpp
)
