set(CPP_FILES
  mitkAbstractSceneReader.cpp
  mitkGeometryDataSerializer.cpp
  mitkImageSerializer.cpp
  mitkPointSetSerializer.cpp
  mitkPropertyListDeserializer.cpp
  mitkPropertyListDeserializerV1.cpp
  mitkSceneFileUtil.cpp
  mitkSceneIO.cpp
  mitkSceneJsonReader.cpp
  mitkSceneReader.cpp
  mitkSceneReaderV1.cpp
  mitkSurfaceSerializer.cpp
)
