set(Plugin-Name "Dicom Inspector Plugin")
set(Plugin-Version "1.0")
set(Plugin-Vendor "DKFZ, Medical and Biological Informatics")
set(Plugin-ContactAddress "")
set(Require-Plugin org.mitk.gui.qt.common)
