/*============================================================================

The Medical Imaging Interaction Toolkit (MITK)

Copyright (c) German Cancer Research Center (DKFZ)
All rights reserved.

Use of this source code is governed by a 3-clause BSD license that can be
found in the LICENSE file.

============================================================================*/


#ifndef QmitkDataGenerationJobBase_h
#define QmitkDataGenerationJobBase_h


//QT
#include <QRunnable>
#include <QObject>
#include <QMetaType>

//MITK
#include <mitkBaseData.h>

#include <MitkImageStatisticsUIExports.h>

/**
 * \brief Base class for background data generation jobs used by QmitkDataGeneratorBase and derived classes.
 *
 * This class combines QObject (for signal/slot communication) and QRunnable (for thread pool execution)
 * to provide a foundation for asynchronous data generation tasks. Derived classes implement RunComputation()
 * to perform the actual work. The run() method handles error management, sets status flags, and emits
 * appropriate signals when results are available or errors occur.
 *
 * \sa QmitkDataGeneratorBase
 * \sa QmitkImageStatisticsCalculationRunnable
 */
class MITKIMAGESTATISTICSUI_EXPORT QmitkDataGenerationJobBase : public QObject, public QRunnable
{
    Q_OBJECT

public:
  /**
   * \brief Map type for results produced by the job.
   *
   * The key is a job-specific label identifying each result (e.g. "statistics"),
   * and the value is the corresponding mitk::BaseData output.
   */
  using ResultMapType = std::map<std::string, mitk::BaseData::Pointer>;

  /**
   * \brief Returns all results generated by this job.
   * \return A map of label-to-result pairs produced by the computation.
   */
  virtual ResultMapType GetResults() const = 0;

  /**
   * \brief Executes the job computation with error handling and result signalling.
   *
   * Calls RunComputation() internally. On success, emits ResultsAvailable with the computed results.
   * On failure or exception, emits Error with a descriptive message. This method is marked final
   * and should not be overridden; override RunComputation() instead.
   */
  void run() final;

  /**
   * \brief Returns whether the last computation completed successfully.
   * \return True if RunComputation() returned true; false otherwise.
   */
  bool GetComputationSuccessFlag() const;

  /**
   * \brief Returns the error message from the last failed computation.
   * \return A string describing the last error, or an empty string if no error occurred.
   */
  std::string GetLastErrorMessage() const;

  /**
   * \brief Returns whether the job is currently executing.
   * \return True if run() is currently in progress; false otherwise.
   */
  bool IsRunning() const;

signals:
    /**
     * \brief Emitted when an error occurs during computation.
     * \param[in] err A human-readable error description.
     * \param[in] job Pointer to the job that encountered the error.
     */
    void Error(QString err, const QmitkDataGenerationJobBase* job);
    /**
     * \brief Emitted when computation results are available.
     * \param[in] results The map of labeled results produced by the job.
     * \param[in] job Pointer to the job that produced the results.
     */
    void ResultsAvailable(ResultMapType results, const QmitkDataGenerationJobBase* job);
    
protected:
  QmitkDataGenerationJobBase() = default;

  virtual ~QmitkDataGenerationJobBase() = default;

  /**Does the real computation. Returns true if there where results produced.*/
  virtual bool RunComputation() = 0;

  std::string m_LastErrorMessage;

private:
  bool m_ComputationSuccessful = false;
  bool m_IsRunning = false;
};

#endif
