set(Plugin-Name "MITK Pointset Interaction")
set(Plugin-Version "0.9")
set(Plugin-Vendor "German Cancer Research Center (DKFZ)")
set(Plugin-ContactAddress "http://www.mitk.org")
set(Require-Plugin org.mitk.gui.qt.common)
