set(Plugin-Name "MITK Pointset Interaction")
set(Plugin-Version "0.9")
set(Plugin-Vendor "DKFZ, Medical and Biological Informatics")
set(Plugin-ContactAddress "http://www.mitk.org")
set(Require-Plugin org.mitk.gui.qt.common.legacy)