SET(MODULE_TESTS
  mitkToFCameraMITKPlayerControllerTest.cpp
  mitkToFCameraMITKPlayerDeviceTest.cpp
  mitkToFCameraPMDCamBoardControllerTest.cpp
  mitkToFCameraPMDCamBoardDeviceTest.cpp
  mitkToFCameraPMDCamCubeControllerTest.cpp
  mitkToFCameraPMDCamCubeDeviceTest.cpp
  mitkToFCameraPMDControllerTest.cpp
  mitkToFCameraPMDDeviceTest.cpp
  mitkToFCameraPMDMITKPlayerControllerTest.cpp
  mitkToFCameraPMDMITKPlayerDeviceTest.cpp
  mitkToFCameraPMDO3ControllerTest.cpp
  mitkToFCameraPMDO3DeviceTest.cpp
  mitkToFCameraPMDPlayerControllerTest.cpp
  mitkToFCameraPMDPlayerDeviceTest.cpp
  mitkToFImageCsvWriterTest.cpp
  mitkToFImageGrabberTest.cpp
  mitkToFImageGrabberCreatorTest.cpp
  mitkToFImageRecorderTest.cpp
  mitkToFImageRecorderFilterTest.cpp
  mitkToFImageWriterTest.cpp
  mitkToFOpenCVImageGrabberTest.cpp
)

