set(MODULE_IMAGE_TESTS
  mitkExtractImageFilterTest.cpp
)
set(MODULE_TESTIMAGES
  US4DCyl.pic.gz
  Pic3D.pic.gz
  Pic2DplusT.pic.gz
  BallBinary30x30x30.pic.gz
  Png2D-bw.png
  binary.stl
  ball.stl
)
