SET(CPP_FILES
  SpaceNavigator/mitkSpaceNavigatorAddOn.cpp
  SpaceNavigator/mitkSpaceNavigatorDriver.cpp
  SpaceNavigator/mitkSpaceNavigatorEvent.cpp
  SpaceNavigator/mitkSpaceNavigatorVtkCameraController.cpp
  )
SET(CPP_FILES
  WiiMote/mitkWiiMoteAddOn.cpp
  )
