set(Plugin-Name "BlueBerry Legacy Compatibility Plugin")
set(Plugin-Version "1.0.0")
set(Plugin-Vendor "DKFZ, Medical and Biological Informatics")
set(Plugin-ContactAddress "http://www.mitk.org")
SET(Require-Plugin "org.blueberry.osgi")
SET(Plugin-ActivationPolicy "eager")
