# @FUNCTIONALITY_NAME@

SET( APPMOD_H ${APPMOD_H} @FUNCTIONALITY_NAME@.h )
SET( APPMOD_MOC_H ${APPMOD_MOC_H} @FUNCTIONALITY_NAME@.h )
SET( APPMOD_CPP ${APPMOD_CPP} @FUNCTIONALITY_NAME@.cpp )
SET (APPMOD_FORMS ${APPMOD_FORMS} @FUNCTIONALITY_NAME@Controls.ui)

