set(CPP_FILES
  mitkBilateralFilter.cpp
)
set(H_FILES
  itkLocalVariationImageFilter.h
  itkLocalVariationImageFilter.tpp
  itkTotalVariationDenoisingImageFilter.h
  itkTotalVariationDenoisingImageFilter.tpp
  itkTotalVariationSingleIterationImageFilter.h
  itkTotalVariationSingleIterationImageFilter.tpp
  mitkBilateralFilter.h
)
