SET(CPP_FILES
QmitkAbortEventFilter.cpp
QmitkApplicationCursor.cpp
QmitkDataStorageComboBox.cpp
QmitkDataStorageListModel.cpp
QmitkDataStorageTableModel.cpp
QmitkDataStorageTreeModel.cpp
QmitkLevelWindowPresetDefinitionDialog.cpp
QmitkLevelWindowRangeChangeDialog.cpp
QmitkLevelWindowWidgetContextMenu.cpp
QmitkLevelWindowWidget.cpp
QmitkLineEditLevelWindowWidget.cpp
# QmitkMaterialEditor.cpp
# QmitkMaterialShowcase.cpp
QmitkPointListModel.cpp
QmitkPointListView.cpp
QmitkPointListWidget.cpp
QmitkPropertiesTableEditor.cpp
QmitkPropertiesTableModel.cpp
QmitkPropertyDelegate.cpp
QmitkRegisterClasses.cpp
QmitkRenderingManager.cpp
QmitkRenderingManagerFactory.cpp
QmitkRenderWindow.cpp
QmitkSliderLevelWindowWidget.cpp
QmitkStdMultiWidget.cpp
)
SET(MOC_H_FILES
QmitkAbortEventFilter.h
QmitkApplicationCursor.h
QmitkDataStorageComboBox.h
QmitkDataStorageListModel.h
QmitkDataStorageTableModel.h
QmitkDataStorageTreeModel.h
QmitkEnums.h
QmitkLevelWindowPresetDefinitionDialog.h
QmitkLevelWindowRangeChangeDialog.h
QmitkLevelWindowWidgetContextMenu.h
QmitkLevelWindowWidget.h
QmitkLineEditLevelWindowWidget.h
# QmitkMaterialEditor.h
QmitkMaterialShowcase.h
QmitkPointListModel.h
QmitkPointListView.h
QmitkPointListWidget.h
QmitkPropertiesTableEditor.h
QmitkPropertiesTableModel.h
QmitkPropertyDelegate.h
QmitkRegisterClasses.h
QmitkRenderingManagerFactory.h
QmitkRenderingManager.h
QmitkRenderWindow.h
QmitkSliderLevelWindowWidget.h
QmitkStdMultiWidget.h
)
SET(UI_FILES
QmitkLevelWindowPresetDefinition.ui  QmitkLevelWindowWidget.ui  QmitkMaterialShowcase.ui
QmitkLevelWindowRangeChange.ui       QmitkMaterialEditor.ui     QmitkStdMultiWidget.ui
)

