SET(CPP_FILES
QmitkAbortEventFilter.cpp
QmitkApplicationCursor.cpp
QmitkDataStorageComboBox.cpp
QmitkDataStorageListModel.cpp
QmitkDataStorageTableModel.cpp
QmitkDataStorageTreeModel.cpp
QmitkEventAdapter.cpp
QmitkLevelWindowPresetDefinitionDialog.cpp
QmitkLevelWindowRangeChangeDialog.cpp
QmitkLevelWindowWidgetContextMenu.cpp
QmitkLevelWindowWidget.cpp
QmitkLineEditLevelWindowWidget.cpp
# QmitkMaterialEditor.cpp
# QmitkMaterialShowcase.cpp
QmitkMemoryUsageIndicatorView.cpp
QmitkRenderWindowMenu.cpp
QmitkPropertiesTableEditor.cpp
QmitkPropertiesTableModel.cpp
QmitkPropertyDelegate.cpp
QmitkRegisterClasses.cpp
QmitkRenderingManager.cpp
QmitkRenderingManagerFactory.cpp
QmitkRenderWindow.cpp
QmitkSliderLevelWindowWidget.cpp
QmitkStdMultiWidget.cpp
)
SET(MOC_H_FILES
QmitkDataStorageComboBox.h
QmitkDataStorageTableModel.h
QmitkLevelWindowPresetDefinitionDialog.h
QmitkLevelWindowRangeChangeDialog.h
QmitkLevelWindowWidgetContextMenu.h
QmitkLevelWindowWidget.h
QmitkLineEditLevelWindowWidget.h
# QmitkMaterialEditor.h
# QmitkMaterialShowcase.h
QmitkMemoryUsageIndicatorView.h
QmitkRenderWindowMenu.h
QmitkPropertiesTableEditor.h
QmitkPropertyDelegate.h
QmitkRenderingManager.h
QmitkRenderWindow.h
QmitkSliderLevelWindowWidget.h
QmitkStdMultiWidget.h
)
SET(UI_FILES
QmitkLevelWindowPresetDefinition.ui
QmitkLevelWindowWidget.ui
QmitkLevelWindowRangeChange.ui
QmitkMemoryUsageIndicator.ui
)

SET(RES_FILES
  #icon/Rendering.qrc
)
