SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${PROJECT_SOURCE_DIR}/openCherry/CMake)
FIND_PACKAGE(Poco)
LIST(APPEND ALL_INCLUDE_DIRECTORIES ${Poco_INCLUDE_DIRS})
LIST(APPEND ALL_LIBRARIES ${Poco_LIBRARIES})
link_directories(${Poco_LIBRARY_DIRS})

 
