FIND_PACKAGE(ITK)
LIST(APPEND ALL_INCLUDE_DIRECTORIES ${ITK_INCLUDE_DIRS})
LIST(APPEND ALL_LIBRARIES ${ITK_LIBRARIES})
link_directories(${ITK_LIBRARY_DIRS})
IF(ITK_USE_SYSTEM_GDCM)
  FIND_PACKAGE(GDCM PATHS ${ITK_GDCM_DIR})
  LIST(APPEND ALL_INCLUDE_DIRECTORIES ${GDCM_INCLUDE_DIRS})
  LIST(APPEND ALL_LIBRARIES ${GDCM_LIBRARIES})
  link_directories(${ITK_GDCM_DIR}/bin)
ENDIF(ITK_USE_SYSTEM_GDCM)

 
