MACRO(MACRO_CREATE_MITK_PLUGIN)

  INCLUDE_DIRECTORIES(${MITK_INCLUDE_DIRS})
  LINK_DIRECTORIES(${MITK_LINK_DIRECTORIES})
  
  MACRO_CREATE_PLUGIN()

  TARGET_LINK_LIBRARIES(${PLUGIN_TARGET} ${MITK_LIBRARIES})

ENDMACRO(MACRO_CREATE_MITK_PLUGIN)


MACRO(MACRO_CREATE_QMITK_PLUGIN)

  INCLUDE_DIRECTORIES(${QMITK_INCLUDE_DIRS})
  LINK_DIRECTORIES(${QMITK_LINK_DIRECTORIES})
  
  MACRO_CREATE_QT_PLUGIN()

  TARGET_LINK_LIBRARIES(${PLUGIN_TARGET} ${QMITK_LIBRARIES})

ENDMACRO(MACRO_CREATE_QMITK_PLUGIN)
