MACRO(MACRO_CREATE_MITK_PLUGIN)
  MITK_CHECK_MODULE(_MODULE_CHECK_RESULT Mitk ${ARGN})
  IF(NOT _MODULE_CHECK_RESULT)
  MITK_USE_MODULE(Mitk ${ARGN})
 
  INCLUDE_DIRECTORIES(${ALL_INCLUDE_DIRECTORIES})
  MACRO_CREATE_PLUGIN()

  TARGET_LINK_LIBRARIES(${PLUGIN_TARGET} ${ALL_LIBRARIES})
  ELSE(NOT _MODULE_CHECK_RESULT)
    MESSAGE("Warning: ${BUNDLE-SYMBOLICNAME} is missing requirements and won't be built. Missing: ${_MODULE_CHECK_RESULT}")
  ENDIF(NOT _MODULE_CHECK_RESULT)
ENDMACRO()

