MACRO(MACRO_CREATE_MITK_PLUGIN)

  INCLUDE_DIRECTORIES(${${KITNAME}_INCLUDE_DIRS})
  MACRO_CREATE_PLUGIN()

  TARGET_LINK_LIBRARIES(${PLUGIN_TARGET} ${${KITNAME}_CORE_LIBRARIES})
  
ENDMACRO(MACRO_CREATE_MITK_PLUGIN)


MACRO(MACRO_CREATE_QMITK_PLUGIN)

  INCLUDE_DIRECTORIES(${Q${KITNAME}_INCLUDE_DIRS})
  MACRO_CREATE_QT_PLUGIN()

  TARGET_LINK_LIBRARIES(${PLUGIN_TARGET} Qmitk)

ENDMACRO(MACRO_CREATE_QMITK_PLUGIN)