INCLUDE(GetPrerequisites)

#file(GLOB_RECURSE TARGET_LIBRARY_FILE ${MITK_CMAKE_RUNTIME_OUTPUT_DIRECTORY}/*/${MITK_BINARY_MODULE})
find_file(TARGET_LIBRARY_FILE "${MITK_BINARY_MODULE}"
    ${MITK_CMAKE_RUNTIME_OUTPUT_DIRECTORY}/../lib/Release 
    ${MITK_CMAKE_RUNTIME_OUTPUT_DIRECTORY}/../lib  
    ${MITK_CMAKE_RUNTIME_OUTPUT_DIRECTORY}/..
    ${MITK_CMAKE_RUNTIME_OUTPUT_DIRECTORY}
    ${MITK_CMAKE_RUNTIME_OUTPUT_DIRECTORY}/Release)
get_filename_component(TARGET_LIBRARY_DIR ${TARGET_LIBRARY_FILE} DIRECTORY )

#mitkFunctionGetLibrarySearchPaths(MITK_RUNTIME_PATH release)
list(APPEND MITK_RUNTIME_PATH
      "${TARGET_LIBRARY_DIR}")
list(REMOVE_DUPLICATES MITK_RUNTIME_PATH)

get_prerequisites(${TARGET_LIBRARY_FILE} PYTHON_LIB_DEPENDENCIES 1 1 "" "${MITK_RUNTIME_PATH}")

configure_file( "${CONFIGUREBUILDTIME_filename}" "${CONFIGUREBUILDTIME_out_filename}" )
