function(mitkFunctionEnableModules)
  if(MITK_WHITELIST STREQUAL "None")
    foreach(module ${${ARGV0}})
      add_subdirectory(${module})
    endforeach()
  else()
    string(FIND "${MITK_WHITELIST}" " (external)" index REVERSE)

    if(${index} EQUAL -1)
      set(whitelistFile "${MITK_WHITELISTS_PATH}/${whitelistFile}.cmake")
    else()
      string(SUBSTRING "${MITK_WHITELIST}" 0 ${index} whitelistFile)
      set(whitelistFile "${MITK_EXTERNAL_WHITELISTS_PATH}/${whitelistFile}.cmake")
    endif()

    include(${whitelistFile})

    if(NOT DEFINED enabled_modules)
      message(FATAL_ERROR "Variable 'enabled_modules' not set in whitelist file '${whitelistFile}'!")
    endif()

    foreach(module ${${ARGV0}})
      list(FIND enabled_modules ${module} index)
      if(NOT index EQUAL -1)
        add_subdirectory(${module})
      endif()
    endforeach()
  endif()
endfunction()
