set(Plugin-Name "XNAT Plugin")
set(Plugin-Version "0.1")
set(Plugin-Vendor "DKFZ, Medical and Biological Informatics")
set(Plugin-ContactAddress "")
set(Require-Plugin org.mitk.gui.qt.common org.mitk.gui.qt.datamanager)
