set(path "src/qwt_transform.h")
file(STRINGS ${path} contents NEWLINE_CONSUME)
string(REPLACE "QT_STATIC_CONST" "static const" contents ${contents})
set(CONTENTS ${contents})
configure_file(${TEMPLATE_FILE} ${path} @ONLY)

set(path "src/qwt_transform.cpp")
file(STRINGS ${path} contents NEWLINE_CONSUME)
string(REPLACE "QT_STATIC_CONST_IMPL" "const" contents ${contents})
set(CONTENTS ${contents})
configure_file(${TEMPLATE_FILE} ${path} @ONLY)
