set(Plugin-Name "Common Qt Ext Plugin")
set(Plugin-Version "0.1")
set(Plugin-Vendor "DKFZ, Medical and Biological Informatics")
set(Plugin-ContactAddress "http://www.mitk.org")
set(Require-Plugin org.mitk.core.ext org.mitk.gui.qt.application)
