set(CPP_FILES
  QmitkHistogramVisualizationWidget.cpp
  QmitkImageStatisticsCalculationRunnable.cpp
  QmitkImageStatisticsPlotHelper.cpp
  QmitkIntensityProfileVisualizationWidget.cpp
  QmitkImageStatisticsTreeModel.cpp
  QmitkStatisticsModelToStringConverter.cpp
  QmitkImageStatisticsWidget.cpp
  QmitkImageStatisticsTreeItem.cpp
  QmitkDataGenerationJobBase.cpp
  QmitkDataGeneratorBase.cpp
  QmitkImageAndRoiDataGeneratorBase.cpp
  QmitkImageStatisticsDataGenerator.cpp
)

set(UI_FILES
  QmitkHistogramVisualizationWidget.ui
  QmitkIntensityProfileVisualizationWidget.ui
  QmitkImageStatisticsWidget.ui
)
