set(CPP_FILES
  QmitkHistogramVisualizationWidget.cpp
  QmitkImageStatisticsCalculationRunnable.cpp
  QmitkIntensityProfileVisualizationWidget.cpp
  QmitkImageStatisticsTreeModel.cpp
  QmitkStatisticsModelToStringConverter.cpp
  QmitkImageStatisticsWidget.cpp
  QmitkImageStatisticsTreeItem.cpp
  QmitkDataGenerationJobBase.cpp
  QmitkDataGeneratorBase.cpp
  QmitkImageAndRoiDataGeneratorBase.cpp
  QmitkImageStatisticsDataGenerator.cpp
)

set(UI_FILES
  src/QmitkHistogramVisualizationWidget.ui
  src/QmitkIntensityProfileVisualizationWidget.ui
  src/QmitkImageStatisticsWidget.ui
)
