set(CPP_FILES
  Qmitk/QmitkHistogramVisualizationWidget.cpp
  Qmitk/QmitkImageStatisticsCalculationRunnable.cpp
  Qmitk/QmitkIntensityProfileVisualizationWidget.cpp
  Qmitk/QmitkImageStatisticsTreeModel.cpp
  Qmitk/QmitkStatisticsModelToStringConverter.cpp
  Qmitk/QmitkImageStatisticsWidget.cpp
  Qmitk/QmitkImageStatisticsTreeItem.cpp
  Qmitk/QmitkDataGenerationJobBase.cpp
  Qmitk/QmitkDataGeneratorBase.cpp
  Qmitk/QmitkImageAndRoiDataGeneratorBase.cpp
  Qmitk/QmitkImageStatisticsDataGenerator.cpp
)

set(UI_FILES
  src/Qmitk/QmitkHistogramVisualizationWidget.ui
  src/Qmitk/QmitkIntensityProfileVisualizationWidget.ui
  src/Qmitk/QmitkImageStatisticsWidget.ui
)
