set(CPP_FILES
  QmitkAboutDialog/QmitkAboutDialog.cpp
  QmitkPropertyObservers/QmitkBasePropertyView.cpp
  QmitkPropertyObservers/QmitkBoolPropertyWidget.cpp
  QmitkPropertyObservers/QmitkColorPropertyEditor.cpp
  QmitkPropertyObservers/QmitkColorPropertyView.cpp
  QmitkPropertyObservers/QmitkEnumerationPropertyWidget.cpp
  QmitkPropertyObservers/QmitkNumberPropertyEditor.cpp
  QmitkPropertyObservers/QmitkNumberPropertySlider.cpp
  QmitkPropertyObservers/QmitkNumberPropertyView.cpp
  QmitkPropertyObservers/QmitkPropertyViewFactory.cpp
  QmitkPropertyObservers/QmitkStringPropertyEditor.cpp
  QmitkPropertyObservers/QmitkStringPropertyOnDemandEdit.cpp
  QmitkPropertyObservers/QmitkStringPropertyView.cpp
  QmitkPropertyObservers/QmitkUGCombinedRepresentationPropertyWidget.cpp
  qclickablelabel.cpp
  QmitkBoundingObjectWidget.cpp
  QmitkCallbackFromGUIThread.cpp
  QmitkColorTransferFunctionCanvas.cpp
  QmitkCorrespondingPointSetsModel.cpp
  QmitkCorrespondingPointSetsView.cpp
  QmitkCorrespondingPointSetsWidget.cpp
  QmitkCrossWidget.cpp
  QmitkEditPointDialog.cpp
  QmitkFileChooser.cpp
  QmitkGnuplotWidget.cpp
  QmitkHistogram.cpp
  QmitkHistogramJSWidget.cpp
  QmitkHistogramWidget.cpp
  QmitkHotkeyLineEdit.cpp
  QmitkModulesDialog.cpp
  QmitkModuleTableModel.cpp
  QmitkPiecewiseFunctionCanvas.cpp
  QmitkPlotWidget.cpp
  QmitkPlotDialog.cpp
  QmitkPointListModel.cpp
  QmitkPointListView.cpp
  QmitkPointListViewWidget.cpp
  QmitkPointListWidget.cpp
  QmitkPrimitiveMovieNavigatorWidget.cpp
  QmitkSelectableGLWidget.cpp
  QmitkSliceWidget.cpp
  QmitkSliderNavigatorWidget.cpp
  QmitkStandardViews.cpp
  QmitkStepperAdapter.cpp
  QmitkTransferFunctionCanvas.cpp
  QmitkTransferFunctionGeneratorWidget.cpp
  QmitkTransferFunctionWidget.cpp
  QmitkVideoBackground.cpp
  QmitkWebPage.cpp
  QtWidgetsExtRegisterClasses.cpp
)

set(MOC_H_FILES
  QmitkAboutDialog/QmitkAboutDialog.h
  QmitkPropertyObservers/QmitkBasePropertyView.h
  QmitkPropertyObservers/QmitkBoolPropertyWidget.h
  QmitkPropertyObservers/QmitkColorPropertyEditor.h
  QmitkPropertyObservers/QmitkColorPropertyView.h
  QmitkPropertyObservers/QmitkEnumerationPropertyWidget.h
  QmitkPropertyObservers/QmitkNumberPropertyEditor.h
  QmitkPropertyObservers/QmitkNumberPropertySlider.h
  QmitkPropertyObservers/QmitkNumberPropertyView.h
  QmitkPropertyObservers/QmitkStringPropertyEditor.h
  QmitkPropertyObservers/QmitkStringPropertyOnDemandEdit.h
  QmitkPropertyObservers/QmitkStringPropertyView.h
  QmitkPropertyObservers/QmitkUGCombinedRepresentationPropertyWidget.h
  qclickablelabel.h
  QmitkBoundingObjectWidget.h
  QmitkCallbackFromGUIThread.h
  QmitkColorTransferFunctionCanvas.h
  QmitkCorrespondingPointSetsModel.h
  QmitkCorrespondingPointSetsView.h
  QmitkCorrespondingPointSetsWidget.h
  QmitkCrossWidget.h
  QmitkEditPointDialog.h
  QmitkFileChooser.h
  QmitkGnuplotWidget.h
  QmitkHistogramJSWidget.h
  QmitkHistogramWidget.h
  QmitkHotkeyLineEdit.h
  QmitkPiecewiseFunctionCanvas.h
  QmitkPlotWidget.h
  QmitkPointListModel.h
  QmitkPointListView.h
  QmitkPointListViewWidget.h
  QmitkPointListWidget.h
  QmitkPrimitiveMovieNavigatorWidget.h
  QmitkSelectableGLWidget.h
  QmitkSliceWidget.h
  QmitkSliderNavigatorWidget.h
  QmitkStandardViews.h
  QmitkStepperAdapter.h
  QmitkTransferFunctionCanvas.h
  QmitkTransferFunctionGeneratorWidget.h
  QmitkTransferFunctionWidget.h
  QmitkVideoBackground.h
  QmitkWebPage.h
)

set(UI_FILES
  QmitkAboutDialog/QmitkAboutDialogGUI.ui
  QmitkGnuplotWidget.ui
  QmitkPrimitiveMovieNavigatorWidget.ui
  QmitkSelectableGLWidget.ui
  QmitkSliceWidget.ui
  QmitkSliderNavigator.ui
  QmitkTransferFunctionGeneratorWidget.ui
  QmitkTransferFunctionWidget.ui
)

set(QRC_FILES
  resources/QtWidgetsExt.qrc
)
