set(CPP_FILES
  mitkIQuestionWidgetFactory.cpp
  mitkModuleActivator.cpp
  mitkQuestionWidgetFactory.cpp
  QmitkCheckboxesQuestionWidget.cpp
  QmitkDropdownQuestionWidget.cpp
  QmitkForm.cpp
  QmitkLinearScaleQuestionWidget.cpp
  QmitkMultipleChoiceQuestionWidget.cpp
  QmitkParagraphQuestionWidget.cpp
  QmitkQuestionWidget.cpp
  QmitkScreenshotQuestionWidget.cpp
  QmitkScreenshotWidget.cpp
  QmitkShortAnswerQuestionWidget.cpp
)

set(UI_FILES
  QmitkForm.ui
  QmitkScreenshotWidget.ui
)
