set(MODULE_TESTS
  #mitkSmoothedClassProbabilitesTest.cpp
  mitkGIFCurvatureStatisticTest
  mitkGIFFirstOrderHistogramStatisticsTest
  mitkGIFImageDescriptionFeaturesTest
  mitkGIFLocalIntensityTest
  mitkGIFVolumetricDensityStatisticsTest
  mitkGIFVolumetricStatisticsTest
  #mitkGlobalFeaturesTest.cpp
)
