set(Plugin-Name "Command Line Modules")
set(Plugin-Version "0.1")
set(Plugin-Vendor "CMIC, Centre For Medical Image Computing, UCL.")
set(Plugin-ContactAddress "https://www.ucl.ac.uk/medical-image-computing")
set(Require-Plugin org.mitk.gui.qt.common)
